/**
 * Copy used by the small, self-contained Arcade games.  The game boards are
 * intentionally kept as lightweight components and still contain a few
 * presentation labels rather than a full page dictionary.  Keeping these
 * labels here lets the shell translate them without duplicating game logic.
 */
export const englishArcadeRuntime: Record<string, string> = {
  "O painel de partidas será atualizado ao iniciar.": "The game panel will update when you start.",
  "Partida validada pelo servidor.": "Game validated by the server.",
  "Não foi possível encerrar a partida.": "We could not finish the game.",
  "Criando uma sessão segura...": "Creating a secure session…",
  "Clique nas moedas. Uma bomba encerra tudo.": "Click the coins. A bomb ends the run.",
  "Bomba atingida. A partida foi perdida.": "Bomb hit. The game is lost.",
  "Três moedas tocaram o chão. Rodada encerrada.": "Three coins reached the ground. Round over.",
  "Partida não validada.": "Game was not validated.",
  "Não foi possível iniciar.": "We could not start the game.",
  "Não foi possível validar o circuito.": "We could not validate the circuit.",
  "Partida indisponível.": "Game unavailable.",
  "CONECTANDO...": "CONNECTING…",
  "INICIAR PARTIDA": "START GAME",
  "ARCADE ARCADIA · DIFICULDADE PROGRESSIVA": "ARCADIA ARCADE · PROGRESSIVE DIFFICULTY",
  "Minigames de mineração": "Mining minigames",
  "PODER TEMPORÁRIO ATIVO": "TEMPORARY POWER ACTIVE",
  "4 MINIGAMES CONECTADOS": "4 CONNECTED MINIGAMES",
  "Progressão de dificuldade e duração do poder": "Difficulty progression and power duration",
  "PROGRESSÃO DO ARCADE": "ARCADE PROGRESSION",
  "Quanto maior o nível, mais tempo dura o poder": "The higher the level, the longer power lasts",
  "Se um ciclo terminar sem uma vitória, o PC volta ao nível 0.": "If a cycle ends without a win, the PC returns to level 0.",
  "dia": "day",
  "dias": "days",
  "Lista de minigames": "Minigame list",
  "Capture moedas e evite bombas": "Catch coins and avoid bombs",
  "Encontre os pares de moedas": "Find matching coins",
  "Siga o pulso e evite bloqueios": "Follow the pulse and avoid blockers",
  "Combine moedas e crie cascatas": "Match coins and create cascades",
  "ONLINE": "ONLINE",
  "NOVO": "NEW",
  "Tutorial rápido do": "Quick tutorial for",
  "01 · OBJETIVO": "01 · GOAL",
  "02 · EVITE": "02 · AVOID",
  "03 · VITÓRIA": "03 · WIN",
  "04 · VALIDAÇÃO": "04 · VALIDATION",
  "O navegador não entrega poder; o servidor confere o resultado.": "The browser does not grant power; the server verifies the result.",
  "MINIGAME 01 · CAÇA-MOEDAS": "MINIGAME 01 · COIN CATCH",
  "NÍVEL": "LEVEL",
  "PONTOS": "SCORE",
  "TEMPO": "TIME",
  "VIDAS": "LIVES",
  "vidas restantes": "lives remaining",
  "Área do Packet Catch": "Packet Catch area",
  "Bomba: não clique": "Bomb: do not click",
  "CHUVA DE MOEDAS · NÍVEL": "COIN RAIN · LEVEL",
  "Bomba atingida": "Bomb hit",
  "Vidas esgotadas": "Out of lives",
  "Capture as moedas": "Catch the coins",
  "VALOR DAS MOEDAS": "COIN VALUES",
  "Cada clique conta": "Every click counts",
  "BOMBA": "BOMB",
  "3 VIDAS": "3 LIVES",
  "Cada moeda que tocar o chão remove uma vida.": "Each coin that reaches the ground costs one life.",
  "MINIGAME 02 · MEMÓRIA AUTORITATIVA": "MINIGAME 02 · AUTHORITATIVE MEMORY",
  "As moedas são reveladas pelo servidor uma carta por vez.": "The server reveals coins one card at a time.",
  "JOGADAS": "MOVES",
  "Tabuleiro de memória": "Memory board",
  "Validando moeda": "Validating coin",
  "revelada": "revealed",
  "Virar carta de moeda": "Flip coin card",
  "VALIDANDO": "VALIDATING",
  "CRIPTO-MEMÓRIA": "CRYPTO MEMORY",
  "Encontre os pares": "Find the pairs",
  "Memória sob pressão": "Memory under pressure",
  "Encontre todos os pares para vencer.": "Find every pair to win.",
  "Mais pares aparecem nos níveis altos.": "Higher levels reveal more pairs.",
  "O tempo diminui conforme a dificuldade.": "Time decreases with difficulty.",
  "O poder só é emitido após validação.": "Power is issued only after validation.",
  "MINIGAME 03 · REFLEXO": "MINIGAME 03 · REFLEX",
  "Complete a sequência antes do tempo sem tocar nos bloqueios.": "Complete the sequence before time runs out without touching blockers.",
  "PULSOS": "PULSES",
  "Tabuleiro de Circuit Rush": "Circuit Rush board",
  "Núcleo verde: clique": "Green core: click",
  "Circuito vermelho: não clique": "Red circuit: do not click",
  "Circuito inativo": "Inactive circuit",
  "ROTA DE REAÇÃO": "REACTION ROUTE",
  "COMO FUNCIONA": "HOW IT WORKS",
  "Verde avança": "Green advances",
  "Toque apenas no núcleo verde pulsante.": "Tap only the pulsing green core.",
  "Qualquer circuito vermelho encerra a rodada.": "Any red circuit ends the round.",
  "Mais bloqueios aparecem nos níveis altos.": "Higher levels add more blockers.",
  "A velocidade é conferida pelo servidor.": "Speed is checked by the server.",
  "MINIGAME 04 · ESTRATÉGIA": "MINIGAME 04 · STRATEGY",
  "Combine moedas, provoque cascatas e alcance a meta do servidor.": "Match coins, trigger cascades and reach the server target.",
  "META DA RODADA": "ROUND TARGET",
  "Progresso da meta": "Target progress",
  "Tabuleiro Coin Cascade": "Coin Cascade board",
  "TABULEIRO 6 × 6 · META": "6 × 6 BOARD · TARGET",
  "PAINEL DE COMBINAÇÕES": "MATCH PANEL",
  "Moedas da rodada": "Round coins",
  "pontos": "points",
  "combinação normal": "standard match",
  "bônus de linha longa": "long-line bonus",
  "super combinação": "super match",
  "Linhas de 4 e 5+ recebem bônus progressivo.": "Lines of 4 and 5+ receive progressive bonuses.",
  "Novas quedas podem criar cascatas pela sorte.": "New drops can create cascades by chance.",
  "Trocas sem combinação não gastam jogada.": "Swaps without a match do not use a move.",
};

export const spanishArcadeRuntime: Record<string, string> = {
  "O painel de partidas será atualizado ao iniciar.": "El panel del juego se actualizará al comenzar.",
  "Partida validada pelo servidor.": "Partida validada por el servidor.",
  "Não foi possível encerrar a partida.": "No se pudo finalizar la partida.",
  "Criando uma sessão segura...": "Creando una sesión segura…",
  "Clique nas moedas. Uma bomba encerra tudo.": "Haz clic en las monedas. Una bomba termina la partida.",
  "Bomba atingida. A partida foi perdida.": "Bomba alcanzada. Perdiste la partida.",
  "Três moedas tocaram o chão. Rodada encerrada.": "Tres monedas tocaron el suelo. Fin de la ronda.",
  "Partida não validada.": "La partida no fue validada.",
  "Não foi possível iniciar.": "No se pudo iniciar.",
  "Não foi possível validar o circuito.": "No se pudo validar el circuito.",
  "Partida indisponível.": "Partida no disponible.",
  "CONECTANDO...": "CONECTANDO…",
  "INICIAR PARTIDA": "INICIAR PARTIDA",
  "ARCADE ARCADIA · DIFICULDADE PROGRESSIVA": "ARCADE ARCADIA · DIFICULTAD PROGRESIVA",
  "Minigames de mineração": "Minijuegos de minería",
  "PODER TEMPORÁRIO ATIVO": "PODER TEMPORAL ACTIVO",
  "4 MINIGAMES CONECTADOS": "4 MINIJUEGOS CONECTADOS",
  "Progressão de dificuldade e duração do poder": "Progresión de dificultad y duración del poder",
  "PROGRESSÃO DO ARCADE": "PROGRESIÓN DEL ARCADE",
  "Quanto maior o nível, mais tempo dura o poder": "Cuanto mayor sea el nivel, más dura el poder",
  "Se um ciclo terminar sem uma vitória, o PC volta ao nível 0.": "Si un ciclo termina sin una victoria, el PC vuelve al nivel 0.",
  "dia": "día",
  "dias": "días",
  "Lista de minigames": "Lista de minijuegos",
  "Capture moedas e evite bombas": "Captura monedas y evita bombas",
  "Encontre os pares de moedas": "Encuentra los pares de monedas",
  "Siga o pulso e evite bloqueios": "Sigue el pulso y evita bloqueos",
  "Combine moedas e crie cascatas": "Combina monedas y crea cascadas",
  "ONLINE": "EN LÍNEA",
  "NOVO": "NUEVO",
  "Tutorial rápido do": "Tutorial rápido de",
  "01 · OBJETIVO": "01 · OBJETIVO",
  "02 · EVITE": "02 · EVITA",
  "03 · VITÓRIA": "03 · VICTORIA",
  "04 · VALIDAÇÃO": "04 · VALIDACIÓN",
  "O navegador não entrega poder; o servidor confere o resultado.": "El navegador no entrega poder; el servidor verifica el resultado.",
  "MINIGAME 01 · CAÇA-MOEDAS": "MINIJUEGO 01 · CAZA MONEDAS",
  "NÍVEL": "NIVEL",
  "PONTOS": "PUNTOS",
  "TEMPO": "TIEMPO",
  "VIDAS": "VIDAS",
  "vidas restantes": "vidas restantes",
  "Área do Packet Catch": "Área de Packet Catch",
  "Bomba: não clique": "Bomba: no hagas clic",
  "CHUVA DE MOEDAS · NÍVEL": "LLUVIA DE MONEDAS · NIVEL",
  "Bomba atingida": "Bomba alcanzada",
  "Vidas esgotadas": "Sin vidas",
  "Capture as moedas": "Captura las monedas",
  "VALOR DAS MOEDAS": "VALOR DE LAS MONEDAS",
  "Cada clique conta": "Cada clic cuenta",
  "BOMBA": "BOMBA",
  "3 VIDAS": "3 VIDAS",
  "Cada moeda que tocar o chão remove uma vida.": "Cada moneda que toque el suelo quita una vida.",
  "MINIGAME 02 · MEMÓRIA AUTORITATIVA": "MINIJUEGO 02 · MEMORIA AUTORITATIVA",
  "As moedas são reveladas pelo servidor uma carta por vez.": "El servidor revela las monedas, una carta a la vez.",
  "JOGADAS": "JUGADAS",
  "Tabuleiro de memória": "Tablero de memoria",
  "Validando moeda": "Validando moneda",
  "revelada": "revelada",
  "Virar carta de moeda": "Voltear carta de moneda",
  "VALIDANDO": "VALIDANDO",
  "CRIPTO-MEMÓRIA": "CRIPTO-MEMORIA",
  "Encontre os pares": "Encuentra los pares",
  "Memória sob pressão": "Memoria bajo presión",
  "Encontre todos os pares para vencer.": "Encuentra todos los pares para ganar.",
  "Mais pares aparecem nos níveis altos.": "En los niveles altos aparecen más pares.",
  "O tempo diminui conforme a dificuldade.": "El tiempo disminuye con la dificultad.",
  "O poder só é emitido após validação.": "El poder solo se emite después de la validación.",
  "MINIGAME 03 · REFLEXO": "MINIJUEGO 03 · REFLEJOS",
  "Complete a sequência antes do tempo sem tocar nos bloqueios.": "Completa la secuencia antes de que termine el tiempo sin tocar los bloqueos.",
  "PULSOS": "PULSOS",
  "Tabuleiro de Circuit Rush": "Tablero de Circuit Rush",
  "Núcleo verde: clique": "Núcleo verde: haz clic",
  "Circuito vermelho: não clique": "Circuito rojo: no hagas clic",
  "Circuito inativo": "Circuito inactivo",
  "ROTA DE REAÇÃO": "RUTA DE REACCIÓN",
  "COMO FUNCIONA": "CÓMO FUNCIONA",
  "Verde avança": "El verde avanza",
  "Toque apenas no núcleo verde pulsante.": "Toca solo el núcleo verde pulsante.",
  "Qualquer circuito vermelho encerra a rodada.": "Cualquier circuito rojo termina la ronda.",
  "A velocidade é conferida pelo servidor.": "La velocidad es comprobada por el servidor.",
  "MINIGAME 04 · ESTRATÉGIA": "MINIJUEGO 04 · ESTRATEGIA",
  "Combine moedas, provoque cascatas e alcance a meta do servidor.": "Combina monedas, provoca cascadas y alcanza el objetivo del servidor.",
  "META DA RODADA": "OBJETIVO DE LA RONDA",
  "Progresso da meta": "Progreso del objetivo",
  "Tabuleiro Coin Cascade": "Tablero de Coin Cascade",
  "TABULEIRO 6 × 6 · META": "TABLERO 6 × 6 · OBJETIVO",
  "PAINEL DE COMBINAÇÕES": "PANEL DE COMBINACIONES",
  "Moedas da rodada": "Monedas de la ronda",
  "pontos": "puntos",
  "combinação normal": "combinación normal",
  "bônus de linha longa": "bonificación de línea larga",
  "super combinação": "supercombinación",
  "Linhas de 4 e 5+ recebem bônus progressivo.": "Las líneas de 4 y 5+ reciben bonificaciones progresivas.",
  "Novas quedas podem criar cascatas pela sorte.": "Nuevas caídas pueden crear cascadas por azar.",
  "Trocas sem combinação não gastam jogada.": "Los cambios sin combinación no gastan una jugada.",
  // The Operator Center uses its English branch for Spanish; these entries
  // keep that branch fully localized as well.
  "Overview": "Resumen",
  "Level and performance": "Nivel y rendimiento",
  "Referrals": "Referencias",
  "Your link and signups": "Tu enlace y registros",
  "My history": "Mi historial",
  "Rounds, purchases and energy": "Partidas, compras y energía",
  "OPERATOR CENTER · PERSONAL PROGRESS": "CENTRO DEL OPERADOR · PROGRESO PERSONAL",
  "Your Arcadia career": "Tu carrera en Arcadia",
  "Track your level and validated progress in a focused space separate from the season and minigames.": "Sigue tu nivel y tu progreso validado en un espacio enfocado, separado de la temporada y los minijuegos.",
  "ORGANIZED AREAS": "ÁREAS ORGANIZADAS",
  "Server-controlled rewards": "Recompensas controladas por el servidor",
  "Operator center sections": "Secciones del centro del operador",
};

Object.assign(englishArcadeRuntime, {
  "Técnico de Mineração": "Mining Technician",
  "Capture as moedas e nunca clique na bomba.": "Catch the coins and never click the bomb.",
  "Clique nas moedas enquanto elas atravessam a tela.": "Click the coins as they cross the screen.",
  "Permaneça com ao menos uma vida até o cronômetro terminar.": "Keep at least one life until the timer ends.",
  "Evite jogadas extras: elas reduzem a eficiência da recompensa.": "Avoid extra moves: they reduce reward efficiency.",
  "Vire duas cartas por vez e memorize a posição das moedas.": "Flip two cards at a time and remember the coin positions.",
  "Encontre todos os pares antes de o tempo acabar.": "Find all pairs before time runs out.",
  "Qualquer núcleo vermelho encerra a rodada imediatamente.": "Any red core ends the round immediately.",
  "Siga somente os núcleos verdes na ordem indicada.": "Follow only the green cores in the indicated order.",
  "Complete toda a sequência dentro do tempo do servidor.": "Complete the full sequence within the server time limit.",
  "Trocas sem formar uma linha não avançam o tabuleiro.": "Swaps that do not form a line do not advance the board.",
  "Combine três ou mais moedas iguais e provoque cascatas.": "Match three or more identical coins to trigger cascades.",
  "Alcance a meta de pontos antes do tempo ou das jogadas acabarem.": "Reach the score target before time or moves run out.",
  "O painel será atualizado ao iniciar.": "The panel will update when you start.",
  "Circuito processado.": "Circuit processed.",
  "Circuito recusado.": "Circuit rejected.",
  "Circuito vermelho atingido. Corrida encerrada.": "Red circuit hit. Run ended.",
  "Clique no núcleo verde. Vermelho encerra a partida.": "Click the green core. Red ends the game.",
  "Sequência concluída. Validando velocidade...": "Sequence complete. Validating speed…",
  "Siga o pulso verde e não toque nos circuitos vermelhos.": "Follow the green pulse and do not touch red circuits.",
  "Sincronizando o circuito...": "Syncing the circuit…",
  "O estado será carregado ao iniciar.": "The state will load when you start.",
  "Tempo encerrado.": "Time is up.",
  "Todos os pares foram encontrados.": "All pairs found.",
  "Carta recusada.": "Card rejected.",
  "Não foi possível virar.": "We could not flip the card.",
  "Montando um tabuleiro seguro...": "Building a secure board…",
  "Memorize as moedas e encontre todos os pares.": "Memorize the coins and find every pair.",
  "Hash Match indisponível.": "Hash Match is unavailable.",
  "Preparando um tabuleiro exclusivo...": "Preparing a unique board…",
  "Toque em uma moeda e depois em uma vizinha para combinar.": "Tap a coin, then a neighboring coin to match.",
  "Essa troca não formou uma linha. Escolha outra vizinha.": "That swap did not form a line. Choose another neighbor.",
  "Combinação recusada.": "Match rejected.",
  "Rodada conferida pelo servidor.": "Round checked by the server.",
  "Não foi possível validar a rodada.": "We could not validate the round.",
  "Coin Cascade indisponível.": "Coin Cascade is unavailable.",
  "MONTANDO TABULEIRO...": "BUILDING BOARD…",
  "Combine e evolua": "Match and evolve",
  "COMBINAÇÃO": "MATCH",
  "LINHA DE 4": "LINE OF 4",
  "5 moedas · mais chances de cascata": "5 coins · more cascade chances",
  "6 moedas · dificuldade intermediária": "6 coins · intermediate difficulty",
  "7 moedas · combinações mais raras": "7 coins · rarer matches",
  "Carregando seu histórico...": "Loading your history…",
  "Histórico indisponível.": "History unavailable.",
  "Não foi possível carregar seu histórico.": "We could not load your history.",
  "Tudo": "All",
  "Mineração": "Mining",
  "Arcade": "Arcade",
  "Compras": "Purchases",
  "Equipamentos": "Equipment",
  "Energia": "Energy",
  "ÚLTIMOS": "LAST",
  "DIAS · CONTA PESSOAL": "DAYS · PERSONAL ACCOUNT",
  "Seu histórico, sem mistério": "Your history, clearly",
  "Compras, mineração, energia e partidas aparecem em uma única linha do tempo. Os dados vêm da sua conta protegida no servidor.": "Purchases, mining, energy and games appear in one timeline. The data comes from your protected server account.",
  "CONTA ATIVA DESDE": "ACCOUNT ACTIVE SINCE",
  "Último salvamento:": "Last saved:",
  "Resumo dos últimos 30 dias": "Summary of the last 30 days",
  "REGISTROS VERIFICADOS": "VERIFIED RECORDS",
  "ações e partidas confirmadas": "confirmed actions and games",
  "MINERAÇÃO": "MINING",
  "fechamentos registrados": "recorded settlements",
  "vitórias em": "wins in",
  "partidas": "games",
  "PODER TEMPORÁRIO": "TEMPORARY POWER",
  "concedido por partidas concluídas": "granted by completed games",
  "CMA RECEBIDO": "CMA RECEIVED",
  "CMA UTILIZADO": "CMA SPENT",
  "CAIXAS ABERTAS": "CRATES OPENED",
  "STATUS DA AUDITORIA": "AUDIT STATUS",
  "em análise": "under review",
  "Tudo validado": "Everything validated",
  "LINHA DO TEMPO": "TIMELINE",
  "Atividades mais recentes": "Most recent activity",
  "ATUALIZAR": "REFRESH",
  "Filtrar histórico": "Filter history",
  "Nenhuma atividade neste filtro": "No activity in this filter",
  "Quando você jogar, minerar ou organizar a sala, aparecerá aqui.": "When you play, mine or organize your room, it will appear here.",
  "EM ANÁLISE": "UNDER REVIEW",
  "Histórico pessoal autoritativo.": "Authoritative personal history.",
  "Uma tela aberta em outro dispositivo não consegue reescrever estes registros.": "A screen open on another device cannot rewrite these records.",
  "dias e mostra": "days and shows",
  "itens; o ledger econômico completo": "items; the complete economic ledger",
  "permanece preservado para auditoria, sem ser carregado inteiro no navegador.": "remains preserved for audit without loading it all in the browser.",
  "TRANSMISSÃO SEGURA ·": "SECURE TRANSMISSION ·",
  "CLIENTE": "CLIENT",
  "SERVIDOR": "SERVER",
  "ENVIANDO PROVA DA PARTIDA": "SENDING GAME PROOF",
  "Pontuação, tempo e eventos estão sendo conferidos pelo servidor.": "Score, timing and events are being checked by the server.",
  "Partidas Restantes (24h)": "Games Remaining (24h)",
  "Recarga gradual automática": "Automatic gradual recharge",
});

Object.assign(spanishArcadeRuntime, {
  "Técnico de Mineração": "Técnico de Minería",
  "Capture as moedas e nunca clique na bomba.": "Captura las monedas y nunca hagas clic en la bomba.",
  "Clique nas moedas enquanto elas atravessam a tela.": "Haz clic en las monedas mientras cruzan la pantalla.",
  "Permaneça com ao menos uma vida até o cronômetro terminar.": "Conserva al menos una vida hasta que termine el cronómetro.",
  "Evite jogadas extras: elas reduzem a eficiência da recompensa.": "Evita jugadas extra: reducen la eficiencia de la recompensa.",
  "Vire duas cartas por vez e memorize a posição das moedas.": "Voltea dos cartas a la vez y memoriza la posición de las monedas.",
  "Encontre todos os pares antes de o tempo acabar.": "Encuentra todos los pares antes de que se acabe el tiempo.",
  "Qualquer núcleo vermelho encerra a rodada imediatamente.": "Cualquier núcleo rojo termina la ronda de inmediato.",
  "Siga somente os núcleos verdes na ordem indicada.": "Sigue solo los núcleos verdes en el orden indicado.",
  "Complete toda a sequência dentro do tempo do servidor.": "Completa toda la secuencia dentro del tiempo del servidor.",
  "Trocas sem formar uma linha não avançam o tabuleiro.": "Los cambios que no forman una línea no avanzan el tablero.",
  "Combine três ou mais moedas iguais e provoque cascatas.": "Combina tres o más monedas iguales y provoca cascadas.",
  "Alcance a meta de pontos antes do tempo ou das jogadas acabarem.": "Alcanza el objetivo de puntos antes de que termine el tiempo o las jugadas.",
  "O painel será atualizado ao iniciar.": "El panel se actualizará al comenzar.",
  "Circuito processado.": "Circuito procesado.",
  "Circuito recusado.": "Circuito rechazado.",
  "Circuito vermelho atingido. Corrida encerrada.": "Circuito rojo alcanzado. Carrera terminada.",
  "Clique no núcleo verde. Vermelho encerra a partida.": "Haz clic en el núcleo verde. El rojo termina la partida.",
  "Sequência concluída. Validando velocidade...": "Secuencia completada. Validando velocidad…",
  "Siga o pulso verde e não toque nos circuitos vermelhos.": "Sigue el pulso verde y no toques los circuitos rojos.",
  "Sincronizando o circuito...": "Sincronizando el circuito…",
  "O estado será carregado ao iniciar.": "El estado se cargará al comenzar.",
  "Tempo encerrado.": "Tiempo agotado.",
  "Todos os pares foram encontrados.": "Se encontraron todos los pares.",
  "Carta recusada.": "Carta rechazada.",
  "Não foi possível virar.": "No se pudo voltear la carta.",
  "Montando um tabuleiro seguro...": "Preparando un tablero seguro…",
  "Memorize as moedas e encontre todos os pares.": "Memoriza las monedas y encuentra todos los pares.",
  "Hash Match indisponível.": "Hash Match no está disponible.",
  "Preparando um tabuleiro exclusivo...": "Preparando un tablero exclusivo…",
  "Toque em uma moeda e depois em uma vizinha para combinar.": "Toca una moneda y después una vecina para combinar.",
  "Essa troca não formou uma linha. Escolha outra vizinha.": "Ese cambio no formó una línea. Elige otra vecina.",
  "Combinação recusada.": "Combinación rechazada.",
  "Rodada conferida pelo servidor.": "Ronda comprobada por el servidor.",
  "Não foi possível validar a rodada.": "No se pudo validar la ronda.",
  "Coin Cascade indisponível.": "Coin Cascade no está disponible.",
  "MONTANDO TABULEIRO...": "PREPARANDO TABLERO…",
  "Combine e evolua": "Combina y evoluciona",
  "COMBINAÇÃO": "COMBINACIÓN",
  "LINHA DE 4": "LÍNEA DE 4",
  "5 moedas · mais chances de cascata": "5 monedas · más posibilidades de cascada",
  "6 moedas · dificuldade intermediária": "6 monedas · dificultad intermedia",
  "7 moedas · combinações mais raras": "7 monedas · combinaciones más raras",
  "Carregando seu histórico...": "Cargando tu historial…",
  "Histórico indisponível.": "Historial no disponible.",
  "Não foi possível carregar seu histórico.": "No se pudo cargar tu historial.",
  "Tudo": "Todo",
  "Mineração": "Minería",
  "Arcade": "Arcade",
  "Compras": "Compras",
  "Equipamentos": "Equipos",
  "Energia": "Energía",
  "Seu histórico, sem mistério": "Tu historial, sin misterios",
  "CONTA ATIVA DESDE": "CUENTA ACTIVA DESDE",
  "Último salvamento:": "Último guardado:",
  "REGISTROS VERIFICADOS": "REGISTROS VERIFICADOS",
  "ações e partidas confirmadas": "acciones y partidas confirmadas",
  "fechamentos registrados": "cierres registrados",
  "vitórias em": "victorias en",
  "partidas": "partidas",
  "PODER TEMPORÁRIO": "PODER TEMPORAL",
  "concedido por partidas concluídas": "otorgado por partidas completadas",
  "CMA RECEBIDO": "CMA RECIBIDO",
  "CMA UTILIZADO": "CMA UTILIZADO",
  "CAIXAS ABERTAS": "CAJAS ABIERTAS",
  "STATUS DA AUDITORIA": "ESTADO DE LA AUDITORÍA",
  "em análise": "en revisión",
  "Tudo validado": "Todo validado",
  "LINHA DO TEMPO": "LÍNEA DE TIEMPO",
  "Atividades mais recentes": "Actividades más recientes",
  "ATUALIZAR": "ACTUALIZAR",
  "Filtrar histórico": "Filtrar historial",
  "Nenhuma atividade neste filtro": "No hay actividad en este filtro",
  "Quando você jogar, minerar ou organizar a sala, aparecerá aqui.": "Cuando juegues, mines u organices tu sala, aparecerá aquí.",
  "EM ANÁLISE": "EN REVISIÓN",
  "Histórico pessoal autoritativo.": "Historial personal autorizado.",
  "Uma tela aberta em outro dispositivo não consegue reescrever estes registros.": "Una pantalla abierta en otro dispositivo no puede reescribir estos registros.",
  "dias e mostra": "días y muestra",
  "itens; o ledger econômico completo": "elementos; el libro mayor económico completo",
  "permanece preservado para auditoria, sem ser carregado inteiro no navegador.": "se conserva para auditoría sin cargarse completo en el navegador.",
  "TRANSMISSÃO SEGURA ·": "TRANSMISIÓN SEGURA ·",
  "CLIENTE": "CLIENTE",
  "SERVIDOR": "SERVIDOR",
  "ENVIANDO PROVA DA PARTIDA": "ENVIANDO PRUEBA DE LA PARTIDA",
  "Pontuação, tempo e eventos estão sendo conferidos pelo servidor.": "El servidor comprueba la puntuación, el tiempo y los eventos.",
  "Partidas Restantes (24h)": "Partidas restantes (24 h)",
  "Recarga gradual automática": "Recarga gradual automática",
});
