export type AssetType =
  | "miner"
  | "rack"
  | "coin"
  | "room"
  | "uiIcon";

export type AssetManifestEntry = {
  id: string;
  type: AssetType;
  path: string;
  width: number;
  height: number;
  slots: number;
  anchor: { x: number; y: number };
  rarity?: "common" | "uncommon" | "rare" | "epic" | "legendary";
  alt: string;
  version: number;
};

export const assetsManifest = {
  cmaCoin: {
    id: "coin_cma_v1",
    type: "coin",
    path: "/assets/brand/cma-coin.png",
    width: 64,
    height: 64,
    slots: 0,
    anchor: { x: 0.5, y: 0.5 },
    alt: "Moeda CMA dourada com emblema de Arcadia",
    version: 1,
  },
  arcadiaCoin: {
    id: "coin_amc_v1",
    type: "coin",
    path: "/assets/season/arcadia/amc-coin.png",
    width: 64,
    height: 64,
    slots: 0,
    anchor: { x: 0.5, y: 0.5 },
    alt: "Arcadia Coin (AMC), recompensa sazonal não monetária",
    version: 1,
  },
  bitcoin: {
    id: "coin_btc_v1",
    type: "coin",
    path: "/assets/coins/btc.svg",
    width: 32,
    height: 32,
    slots: 0,
    anchor: { x: 0.5, y: 0.5 },
    alt: "Símbolo do Bitcoin",
    version: 1,
  },
  dogecoin: {
    id: "coin_doge_v1",
    type: "coin",
    path: "/assets/coins/doge.svg",
    width: 32,
    height: 32,
    slots: 0,
    anchor: { x: 0.5, y: 0.5 },
    alt: "Símbolo do Dogecoin",
    version: 1,
  },
  ethereum: {
    id: "coin_eth_v1",
    type: "coin",
    path: "/assets/coins/ethereum.png",
    width: 64,
    height: 64,
    slots: 0,
    anchor: { x: 0.5, y: 0.5 },
    alt: "Símbolo do Ethereum",
    version: 1,
  },
  litecoin: {
    id: "coin_ltc_v1",
    type: "coin",
    path: "/assets/coins/ltc.svg",
    width: 32,
    height: 32,
    slots: 0,
    anchor: { x: 0.5, y: 0.5 },
    alt: "Símbolo do Litecoin",
    version: 1,
  },
  xrp: {
    id: "coin_xrp_v1",
    type: "coin",
    path: "/assets/coins/xrp.svg",
    width: 32,
    height: 32,
    slots: 0,
    anchor: { x: 0.5, y: 0.5 },
    alt: "Símbolo do XRP",
    version: 1,
  },
  bnb: {
    id: "coin_bnb_v1",
    type: "coin",
    path: "/assets/coins/binance.png",
    width: 2000,
    height: 2000,
    slots: 0,
    anchor: { x: 0.5, y: 0.5 },
    alt: "Símbolo do BNB",
    version: 1,
  },
  matic: {
    id: "coin_matic_v1",
    type: "coin",
    path: "/assets/coins/matic.svg",
    width: 32,
    height: 32,
    slots: 0,
    anchor: { x: 0.5, y: 0.5 },
    alt: "Símbolo do Polygon",
    version: 1,
  },
  solana: {
    id: "coin_sol_v1",
    type: "coin",
    path: "/assets/coins/solana.png",
    width: 64,
    height: 64,
    slots: 0,
    anchor: { x: 0.5, y: 0.5 },
    alt: "Símbolo da Solana",
    version: 1,
  },
  tron: {
    id: "coin_trx_v1",
    type: "coin",
    path: "/assets/coins/trx.png",
    width: 32,
    height: 32,
    slots: 0,
    anchor: { x: 0.5, y: 0.5 },
    alt: "Símbolo do TRON",
    version: 1,
  },
  tether: {
    id: "coin_usdt_v1",
    type: "coin",
    path: "/assets/coins/usdt.png",
    width: 64,
    height: 64,
    slots: 0,
    anchor: { x: 0.5, y: 0.5 },
    alt: "Símbolo do Tether",
    version: 1,
  },
  monero: {
    id: "coin_xmr_v1",
    type: "coin",
    path: "/assets/coins/xmr.svg",
    width: 32,
    height: 32,
    slots: 0,
    anchor: { x: 0.5, y: 0.5 },
    alt: "Símbolo do Monero",
    version: 1,
  },
  rackBasic: {
    id: "rack_arcadia_basic_v1",
    type: "rack",
    path: "/assets/racks/rack-basic.png",
    width: 252,
    height: 200,
    slots: 8,
    anchor: { x: 0.5, y: 1 },
    alt: "Rack metálico de quatro prateleiras",
    version: 1,
  },
  rackTallStaging: {
    id: "rack_arcadia_tall_staging_v1",
    type: "rack",
    path: "/assets/racks/arcadia-rack-tall-v1.png",
    width: 1024,
    height: 1536,
    slots: 8,
    anchor: { x: 0.5, y: 1 },
    alt: "Rack alto de quatro prateleiras para o ambiente de testes",
    version: 1,
  },
  roomOne: {
    id: "room_arcadia_workshop_v1",
    type: "room",
    path: "/assets/rooms/arcadia-room-01.gif",
    width: 724,
    height: 543,
    slots: 0,
    anchor: { x: 0.5, y: 1 },
    alt: "Oficina de mineração de Arcadia com luzes animadas",
    version: 1,
  },
  roomTwo: {
    id: "room_arcadia_lab_v1",
    type: "room",
    path: "/assets/rooms/arcadia-room-02.gif",
    width: 724,
    height: 543,
    slots: 0,
    anchor: { x: 0.5, y: 1 },
    alt: "Laboratório de mineração de Arcadia",
    version: 1,
  },
  battery: {
    id: "ui_battery_v1",
    type: "uiIcon",
    path: "/assets/ui/battery.png",
    width: 126,
    height: 100,
    slots: 0,
    anchor: { x: 0.5, y: 0.5 },
    alt: "Bateria de energia",
    version: 1,
  },
  pcLevel1: {
    id: "ui_pc_level_1_v1",
    type: "uiIcon",
    path: "/assets/ui/pc-level-1.png",
    width: 192,
    height: 192,
    slots: 0,
    anchor: { x: 0.5, y: 0.5 },
    alt: "Computador Arcadia do nível 1",
    version: 1,
  },
  pcLevel2: {
    id: "ui_pc_level_2_v1",
    type: "uiIcon",
    path: "/assets/ui/pc-level-2.png",
    width: 192,
    height: 192,
    slots: 0,
    anchor: { x: 0.5, y: 0.5 },
    alt: "Computador Arcadia do nível 2",
    version: 1,
  },
  pcLevel3: {
    id: "ui_pc_level_3_v1",
    type: "uiIcon",
    path: "/assets/ui/pc-level-3.png",
    width: 192,
    height: 192,
    slots: 0,
    anchor: { x: 0.5, y: 0.5 },
    alt: "Computador Arcadia do nível 3",
    version: 1,
  },
  pcLevel4: {
    id: "ui_pc_level_4_v1",
    type: "uiIcon",
    path: "/assets/ui/pc-level-4.png",
    width: 192,
    height: 192,
    slots: 0,
    anchor: { x: 0.5, y: 0.5 },
    alt: "Computador Arcadia do nível 4",
    version: 1,
  },
  pcLevel5: {
    id: "ui_pc_level_5_v1",
    type: "uiIcon",
    path: "/assets/ui/pc-level-5.png",
    width: 192,
    height: 192,
    slots: 0,
    anchor: { x: 0.5, y: 0.5 },
    alt: "Computador Arcadia do nível 5",
    version: 1,
  },
  minerOne: {
    id: "miner_byte_spark_v1",
    type: "miner",
    path: "/assets/miners/miner-01.gif",
    width: 74,
    height: 50,
    slots: 1,
    anchor: { x: 0.5, y: 1 },
    rarity: "common",
    alt: "Minerador Byte Spark com uma fan verde",
    version: 1,
  },
  minerTwo: {
    id: "miner_amber_core_v1",
    type: "miner",
    path: "/assets/miners/miner-02.gif",
    width: 74,
    height: 58,
    slots: 1,
    anchor: { x: 0.5, y: 1 },
    rarity: "uncommon",
    alt: "Minerador Amber Core com uma fan âmbar",
    version: 1,
  },
  minerThree: {
    id: "miner_dual_nova_v1",
    type: "miner",
    path: "/assets/miners/miner-03.gif",
    width: 114,
    height: 54,
    slots: 2,
    anchor: { x: 0.5, y: 1 },
    rarity: "rare",
    alt: "Minerador Dual Nova com duas fans",
    version: 1,
  },
  minerFour: {
    id: "miner_cryo_twin_v1",
    type: "miner",
    path: "/assets/miners/miner-04.gif",
    width: 114,
    height: 54,
    slots: 2,
    anchor: { x: 0.5, y: 1 },
    rarity: "rare",
    alt: "Minerador Cryo Twin com duas fans azuis",
    version: 1,
  },
  minerFive: {
    id: "miner_magenta_flux_v1",
    type: "miner",
    path: "/assets/miners/miner-05.gif",
    width: 114,
    height: 54,
    slots: 2,
    anchor: { x: 0.5, y: 1 },
    rarity: "epic",
    alt: "Minerador Magenta Flux com duas fans",
    version: 1,
  },
  minerSix: {
    id: "miner_violet_bit_v1",
    type: "miner",
    path: "/assets/miners/miner-06.gif",
    width: 74,
    height: 50,
    slots: 1,
    anchor: { x: 0.5, y: 1 },
    rarity: "uncommon",
    alt: "Minerador Violet Bit com uma fan roxa",
    version: 1,
  },
  minerSeven: {
    id: "miner_helix_gold_v1",
    type: "miner",
    path: "/assets/miners/miner-07.gif",
    width: 114,
    height: 58,
    slots: 2,
    anchor: { x: 0.5, y: 1 },
    rarity: "legendary",
    alt: "Minerador Helix Gold com duas fans",
    version: 1,
  },
  spaceRover: {
    id: "miner_space_rover_s1",
    type: "miner",
    path: "/assets/seasons/space-race/lunar-rover.gif",
    width: 74,
    height: 50,
    slots: 1,
    anchor: { x: 0.5, y: 1 },
    rarity: "common",
    alt: "Rover lunar da primeira temporada Corrida Espacial",
    version: 1,
  },
  spaceSatellite: {
    id: "miner_space_satellite_s1",
    type: "miner",
    path: "/assets/seasons/space-race/relay-satellite.gif",
    width: 74,
    height: 50,
    slots: 1,
    anchor: { x: 0.5, y: 1 },
    rarity: "uncommon",
    alt: "Satélite de retransmissão da primeira temporada Corrida Espacial",
    version: 1,
  },
  spaceSkiff: {
    id: "miner_space_skiff_s1",
    type: "miner",
    path: "/assets/seasons/space-race/comet-skiff.gif",
    width: 74,
    height: 50,
    slots: 1,
    anchor: { x: 0.5, y: 1 },
    rarity: "uncommon",
    alt: "Nave Comet Skiff da primeira temporada Corrida Espacial",
    version: 1,
  },
  spaceScout: {
    id: "miner_space_scout_s1",
    type: "miner",
    path: "/assets/seasons/space-race/star-scout.gif",
    width: 74,
    height: 50,
    slots: 1,
    anchor: { x: 0.5, y: 1 },
    rarity: "rare",
    alt: "Nave Star Scout da primeira temporada Corrida Espacial",
    version: 1,
  },
  spaceDrill: {
    id: "miner_space_drill_s1",
    type: "miner",
    path: "/assets/seasons/space-race/orbit-drill.gif",
    width: 114,
    height: 62,
    slots: 2,
    anchor: { x: 0.5, y: 1 },
    rarity: "rare",
    alt: "Perfurador orbital da primeira temporada Corrida Espacial",
    version: 1,
  },
  spaceFreighter: {
    id: "miner_space_freighter_s1",
    type: "miner",
    path: "/assets/seasons/space-race/void-freighter.gif",
    width: 114,
    height: 62,
    slots: 2,
    anchor: { x: 0.5, y: 1 },
    rarity: "epic",
    alt: "Cargueiro Void da primeira temporada Corrida Espacial",
    version: 1,
  },
  spaceCruiser: {
    id: "miner_space_cruiser_s1",
    type: "miner",
    path: "/assets/seasons/space-race/plasma-cruiser.gif",
    width: 114,
    height: 62,
    slots: 2,
    anchor: { x: 0.5, y: 1 },
    rarity: "epic",
    alt: "Cruzador Plasma da primeira temporada Corrida Espacial",
    version: 1,
  },
  spaceStation: {
    id: "miner_space_station_s1",
    type: "miner",
    path: "/assets/seasons/space-race/arcadia-station.gif",
    width: 114,
    height: 62,
    slots: 2,
    anchor: { x: 0.5, y: 1 },
    rarity: "legendary",
    alt: "Estação Arcadia da primeira temporada Corrida Espacial",
    version: 1,
  },
  alchemyDesk: {
    id: "miner_alchemy_desk_s2",
    type: "miner",
    path: "/assets/seasons/alchemy/apprentice-desk.gif",
    width: 114,
    height: 86,
    slots: 1,
    anchor: { x: 0.5, y: 1 },
    rarity: "common",
    alt: "Bancada do Aprendiz da segunda temporada Alquimia Mágica",
    version: 1,
  },
  alchemyCrystal: {
    id: "miner_alchemy_crystal_s2",
    type: "miner",
    path: "/assets/seasons/alchemy/floating-crystal.gif",
    width: 96,
    height: 92,
    slots: 1,
    anchor: { x: 0.5, y: 1 },
    rarity: "common",
    alt: "Cristal Flutuante da segunda temporada Alquimia Mágica",
    version: 1,
  },
  alchemyLantern: {
    id: "miner_alchemy_lantern_s2",
    type: "miner",
    path: "/assets/seasons/alchemy/soul-lantern.gif",
    width: 96,
    height: 96,
    slots: 1,
    anchor: { x: 0.5, y: 1 },
    rarity: "common",
    alt: "Lanterna das Almas da segunda temporada Alquimia Mágica",
    version: 1,
  },
  alchemyCauldron: {
    id: "miner_alchemy_cauldron_s2",
    type: "miner",
    path: "/assets/seasons/alchemy/magic-cauldron.gif",
    width: 96,
    height: 96,
    slots: 1,
    anchor: { x: 0.5, y: 1 },
    rarity: "uncommon",
    alt: "Caldeirão Mágico da segunda temporada Alquimia Mágica",
    version: 1,
  },
  alchemyAlembic: {
    id: "miner_alchemy_alembic_s2",
    type: "miner",
    path: "/assets/seasons/alchemy/potion-alembic.gif",
    width: 114,
    height: 96,
    slots: 1,
    anchor: { x: 0.5, y: 1 },
    rarity: "uncommon",
    alt: "Alambique de Poções da segunda temporada Alquimia Mágica",
    version: 1,
  },
  alchemyMana: {
    id: "miner_alchemy_mana_s2",
    type: "miner",
    path: "/assets/seasons/alchemy/mana-generator.gif",
    width: 152,
    height: 104,
    slots: 2,
    anchor: { x: 0.5, y: 1 },
    rarity: "rare",
    alt: "Gerador de Mana da segunda temporada Alquimia Mágica",
    version: 1,
  },
  alchemyOrrery: {
    id: "miner_alchemy_orrery_s2",
    type: "miner",
    path: "/assets/seasons/alchemy/astral-orrery.gif",
    width: 148,
    height: 112,
    slots: 2,
    anchor: { x: 0.5, y: 1 },
    rarity: "rare",
    alt: "Orrery Astral da segunda temporada Alquimia Mágica",
    version: 1,
  },
  alchemySpellbook: {
    id: "miner_alchemy_spellbook_s2",
    type: "miner",
    path: "/assets/seasons/alchemy/spellbook-altar.gif",
    width: 128,
    height: 106,
    slots: 2,
    anchor: { x: 0.5, y: 1 },
    rarity: "epic",
    alt: "Altar do Grimório da segunda temporada Alquimia Mágica",
    version: 1,
  },
  alchemyForge: {
    id: "miner_alchemy_forge_s2",
    type: "miner",
    path: "/assets/seasons/alchemy/transmutation-forge.gif",
    width: 168,
    height: 112,
    slots: 2,
    anchor: { x: 0.5, y: 1 },
    rarity: "epic",
    alt: "Forja de Transmutação da segunda temporada Alquimia Mágica",
    version: 1,
  },
  alchemyTower: {
    id: "miner_alchemy_tower_s2",
    type: "miner",
    path: "/assets/seasons/alchemy/wizard-tower.gif",
    width: 124,
    height: 124,
    slots: 2,
    anchor: { x: 0.5, y: 1 },
    rarity: "legendary",
    alt: "Torre do Arcanista da segunda temporada Alquimia Mágica",
    version: 1,
  },
  pixelEnergy: {
    id: "ui_pixel_energy_v1",
    type: "uiIcon",
    path: "/pixel-energy.jpg",
    width: 126,
    height: 100,
    slots: 0,
    anchor: { x: 0.5, y: 0.5 },
    alt: "Energia Temporária",
    version: 1,
  },
  roomOneStaging: {
    id: "room_arcadia_workshop_staging_v1",
    type: "room",
    // Staging uses the extended floor plate so racks start below the
    // workstation instead of covering the operator and background art.
    path: "/assets/rooms/tall-room-staging.jpg",
    width: 896,
    height: 1200,
    slots: 0,
    anchor: { x: 0.5, y: 1 },
    alt: "Oficina de mineração de Arcadia (Staging)",
    version: 1,
  },
  roomTwoStaging: {
    id: "room_arcadia_lab_staging_v1",
    type: "room",
    path: "/assets/rooms/staging-room-02.gif",
    width: 1206,
    height: 840,
    slots: 0,
    anchor: { x: 0.5, y: 1 },
    alt: "Laboratório de mineração de Arcadia (Staging)",
    version: 1,
  },
} satisfies Record<string, AssetManifestEntry>;
