export const spanishRuntime: Record<string, string> = {
  "100–220 temporary GH/s": "100–220 GH/s temporales",
  "Account and access": "Cuenta y acceso",
  "Can CMA be withdrawn?": "¿Se puede retirar la CMA?",
  "180–350 temporary GH/s": "180–350 GH/s temporal",
  "Balances, deposits and conversion": "Saldos, depósitos y conversión",
  "CLAIMED": "RECLAMADO",
  "Account shortcuts": "Accesos directos a cuentas",
  "Check your inbox": "Revisa tu bandeja de entrada",
  "characters": "personajes",
  "140–280 temporary GH/s": "140–280 GH/s temporales",
  "Attempt limit reached. Request a new code.": "Se alcanzó el límite de intentos. Solicite un nuevo código.",
  "ACCOUNT REQUIRED": "CUENTA REQUERIDA",
  "Claim the Tour battery in the Operator Center": "Reclama la batería del Tour en el Centro del Operador",
  "2–3 minutes": "2-3 minutos",
  "Accept the Terms and Privacy Policy to continue.": "Acepte los Términos y la Política de Privacidad para continuar.",
  "BASIC": "BÁSICO",
  "A new QR code was generated. Scan it in your authenticator app and confirm the code.": "Se generó un nuevo código QR. Escanéelo en su aplicación de autenticación y confirme el código.",
  "At least 10 characters.": "Al menos 10 caracteres.",
  "Account guide and alerts": "Guía de cuenta y alertas.",
  "After confirmation, you can convert whole units to CMA.": "Después de la confirmación, puede convertir unidades enteras a CMA.",
  "${rackInventoryCount} rack available": "${rackInventoryCount} estante disponible",
  "10-minute block": "bloque de 10 minutos",
  "CHOOSE HOW MANY CMA TO BUY": "ELIJA CUÁNTOS CMA COMPRAR",
  "Balance protected by the server": "Saldo protegido por el servidor",
  "Back to sign in": "Volver para iniciar sesión",
  "Close tour": "Cerrar recorrido",
  "Balances and conversions": "Saldos y conversiones",
  "battery(ies) available in inventory.": "batería(s) disponibles en el inventario.",
  "Action rejected.": "Acción rechazada.",
  "Account access": "Acceso a la cuenta",
  "After ${data.proposal.eligibilityHours} hours and ${data.proposal.minimumCompletedGames} completed games, the bonus is credited block by block. The invited operator keeps the full block reward; no balance is accumulated and the program does not change the fixed reward per block.": "Después de ${data.proposal.eligibilityHours} horas y ${data.proposal.minimumCompletedGames} juegos completos, el bono se acredita bloque por bloque. El operador invitado se queda con la recompensa del bloque completo; no se acumula saldo y el programa no cambia la recompensa fija por bloque.",
  "ACCOUNT SECURITY": "SEGURIDAD DE LA CUENTA",
  "Block closing soon": "El bloque se cerrará pronto",
  "3. Check the ledger": "3. Consulta el libro mayor",
  "ACTIVE AND REGISTERED": "ACTIVO Y REGISTRADO",
  "${100 - totalAllocation}% REMAINING": "${100 - asignación total}% RESTANTE",
  "BALANCE": "BALANCE",
  "ALLOCATION": "ASIGNACIÓN",
  "ACCOUNT SETUP": "CONFIGURACIÓN DE CUENTA",
  "Click to change.": "Haga clic para cambiar.",
  "A code was already sent. Wait a moment before requesting another.": "Ya se envió un código. Espere un momento antes de solicitar otro.",
  "Arcadia highlights": "Lo más destacado de Arcadia",
  "ADJUST DISTRIBUTION": "AJUSTAR LA DISTRIBUCIÓN",
  "${totalAllocation - 100}% OVER": "${totalAllocation - 100}% SUPERIOR",
  "Account details": "Detalles de la cuenta",
  "After network confirmation, the operation status updates automatically.": "Después de la confirmación de la red, el estado de la operación se actualiza automáticamente.",
  "Arcadia never asks for your private key.": "Arcadia nunca solicita su clave privada.",
  "CLAIMING...": "RECLAMANDO...",
  "A code will be requested on new sign-ins.": "Se solicitará un código en nuevos inicios de sesión.",
  "CLICK TO MANAGE": "HAGA CLIC PARA GESTIONAR",
  "ARCADIA WALLET": "BILLETERA ARCADIA",
  "Account is organized. No urgent action right now.": "La cuenta está organizada. No hay ninguna acción urgente en este momento.",
  "${chargedCells} of 8 cells charged": "${chargedCells} de 8 celdas cargadas",
  "Claim failed.": "Reclamación fallida.",
  "Choose a rack slot": "Elija una ranura para bastidor",
  "CLOSE": "CERCA",
  "${tickets.length} RECENT": "${tickets.length} RECIENTE",
  "Arcadia support never asks for your password, authentication code, or private key.": "El soporte de Arcadia nunca le solicita su contraseña, código de autenticación o clave privada.",
  "Choose fiat or crypto": "Elija fiat o cripto",
  "balance": "balance",
  "BUY MAXIMUM WHOLE AMOUNT": "COMPRAR CANTIDAD TOTAL MÁXIMA",
  "ACCOUNT RECOVERY": "RECUPERACIÓN DE CUENTA",
  "BASE EMISSION": "EMISIÓN BÁSICA",
  "60–90 seconds": "60 a 90 segundos",
  "90–120 seconds": "90-120 segundos",
  "Authenticator code": "código de autenticación",
  "ALLOCATED": "ASIGNADO",
  "CHECKING QUOTE…": "COMPROBANDO COTIZACIÓN…",
  "BATTERY": "BATERÍA",
  "CLAIM XP": "RECLAMAR XP",
  "6-digit code": "código de 6 dígitos",
  "4. Convert when you want": "4. Convierte cuando quieras",
  "Change password": "Cambiar la contraseña",
  "CLAIM · MAX": "RECLAMACIÓN · MÁXIMO",
  "CHECK THE ASSET, NETWORK AND ADDRESS BEFORE SENDING.": "COMPRUEBE EL ACTIVO, LA RED Y LA DIRECCIÓN ANTES DE ENVIAR.",
  "Battery available": "Batería disponible",
  "A setup is already in progress. Continue with the code shown in your authenticator app.": "Ya hay una configuración en progreso. Continúe con el código que se muestra en su aplicación de autenticación.",
  "AMOUNT IN ${withdrawAsset}": "CANTIDAD EN ${withdrawAsset}",
  "Close block notice": "Cerrar aviso de bloqueo",
  "Choose a whole CMA amount and review the final value.": "Elija un monto total de CMA y revise el valor final.",
  "2. Wait for confirmation": "2. Espere la confirmación",
  "BACK TO SIGN IN": "VOLVER A INICIAR SESIÓN",
  "ACTIVE SEASON": "TEMPORADA ACTIVA",
  "ARCADIA ACCOUNT": "CUENTA ARCADIA",
  "ACTIVE": "ACTIVO",
  "Close": "Cerca",
  "CMA REFERENCE": "REFERENCIA CMA",
  "CLAIM": "AFIRMAR",
  "24h estimate": "estimación 24h",
  "Back to the room": "De vuelta a la habitación",
  "ARCADIA REPLY": "RESPUESTA DE ARCADIA",
  "1. Choose the coin": "1. Elige la moneda",
  "CLAIM REWARD": "RECLAMAR RECOMPENSA",
  "CANCEL": "CANCELAR",
  "Close operations panel": "Cerrar panel de operaciones",
  "CHECK THE PIX KEY AND QUOTED AMOUNT.": "VERIFICA LA CLAVE PIX Y EL IMPORTE COTIZADO.",
  "CLOSED": "CERRADO",
  "batteries in inventory": "baterías en inventario",
  "Choose how you want to receive": "Elige cómo quieres recibir",
  "Build and test fun without rewards.": "Crea y prueba diversión sin recompensas.",
  "Gameplay": "Jugabilidad",
  "Display name": "Nombre para mostrar",
  "Email": "Correo electrónico",
  "DAY": "DÍA",
  "Common topics and account safety": "Temas comunes y seguridad de la cuenta",
  "Confirm your email": "Confirma tu correo electrónico",
  "Code sent. Check your inbox and spam folder.": "Código enviado. Revisa tu bandeja de entrada y carpeta de spam.",
  "Continue": "Continuar",
  "distributed": "repartido",
  "CONFIRM AND SEND FOR REVIEW": "CONFIRMAR Y ENVIAR PARA REVISIÓN",
  "CONTINUE": "CONTINUAR",
  "complete": "completo",
  "Confirm password": "Confirmar Contraseña",
  "Disable two-step authentication on this account?": "¿Desactivar la autenticación de dos pasos en esta cuenta?",
  "Crypto statement updated.": "Declaración criptográfica actualizada.",
  "comfortable": "cómodo",
  "Connection error.": "Error de conexión.",
  "Essential rewards for everyone": "Recompensas esenciales para todos",
  "DEPOSITS": "DEPÓSITOS",
  "COMFORTABLE": "CÓMODO",
  "CONTINUE WITH GOOGLE": "CONTINUAR CON GOOGLE",
  "Confirm new password": "Confirmar nueva contraseña",
  "CONFIRMATION": "CONFIRMACIÓN",
  "EXTRA LARGE": "EXTRA GRANDE",
  "Confirmation code": "Código de confirmación",
  "Does the game guarantee financial returns?": "¿El juego garantiza rentabilidad financiera?",
  "ENERGY": "ENERGÍA",
  "DISABLE": "DESACTIVAR",
  "DAILY": "A DIARIO",
  "Duration": "Duración",
  "Daily Login Bonus": "Bono de inicio de sesión diario",
  "Create account": "Crear una cuenta",
  "Forgot my password": "Olvidé mi contraseña",
  "en-US": "es-US",
  "extra large": "extra grande",
  "CONFIRM AND CONTINUE": "CONFIRMAR Y CONTINUAR",
  "Equip a miner": "Equipar un minero",
  "GET 2-MINUTE QUOTE": "OBTENER COTIZACIÓN DE 2 MINUTOS",
  "Complete a minigame": "Completa un minijuego",
  "Distribute your power": "Distribuye tu poder",
  "game(s) recorded": "juego(s) grabado(s)",
  "CONVERT TO CMA": "CONVERTIR A CMA",
  "Contact our team": "Contacta con nuestro equipo",
  "Game and inventory": "Juego e inventario",
  "Expected power": "potencia esperada",
  "CONFIRMATION REQUESTED": "CONFIRMACIÓN SOLICITADA",
  "Complete the Arcade Tour": "Completa el recorrido arcade",
  "Controlled economy": "Economía controlada",
  "DEPOSIT": "DEPÓSITO",
  "FIRST DAY · OPERATOR KIT": "PRIMER DÍA · KIT ​​DE OPERADOR",
  "FIXED NETWORK BLOCK · 10 MIN": "BLOQUE DE RED FIJA · 10 MIN",
  "equipment item(s) operating": "elemento(s) del equipo en funcionamiento",
  "Effective allocated power": "Poder asignado efectivo",
  "FREE BATTERY · 12H CYCLE": "BATERÍA GRATIS · CICLO 12H",
  "Email delivery is temporarily unavailable. Try again later.": "La entrega de correo electrónico no está disponible temporalmente. Vuelve a intentarlo más tarde.",
  "Confirm the human verification to resend.": "Confirma la verificación humana para reenviar.",
  "CONVERT AND RECEIVE VIA PIX": "CONVERTIR Y RECIBIR A TRAVÉS DE PIX",
  "DESIGN PHASE · REWARDS DISABLED": "FASE DE DISEÑO · RECOMPENSAS DESHABILITADAS",
  "FIRST ACCESS · OPERATOR TOUR": "PRIMER ACCESO · TOUR DEL OPERADOR",
  "Email confirmation is required.": "Se requiere confirmación por correo electrónico.",
  "Confirm the human verification to continue.": "Confirma la verificación humana para continuar.",
  "Distribute 100% of your power": "Distribuye el 100% de tu poder",
  "CREATING...": "CREANDO...",
  "Cycle complete": "Ciclo completo",
  "Earn and activate energy": "Gana y activa energía",
  "CREATE ACCOUNT AND START": "CREAR CUENTA Y COMENZAR",
  "CURRENT OPERATIONS": "OPERACIONES ACTUALES",
  "days to reach Deep Space": "días para llegar al espacio profundo",
  "CREATE TICKET": "CREAR BOLETO",
  "Displayed balance": "Saldo mostrado",
  "Global player power": "Poder del jugador global",
  "COPY LINK": "COPIAR ENLACE",
  "Create your new password": "Crea tu nueva contraseña",
  "FREQUENT QUESTIONS": "PREGUNTAS FRECUENTES",
  "EQUAL SPLIT": "DIVISIÓN IGUAL",
  "Confirm your presence before requesting another email.": "Confirma tu presencia antes de solicitar otro correo electrónico.",
  "energy cycle": "ciclo energético",
  "FREE POSITIONS": "PUESTOS LIBRES",
  "ENABLE AUTHENTICATOR": "HABILITAR AUTENTICADOR",
  "global pools": "piscinas globales",
  "FREE PASS": "PASE LIBRE",
  "ECONOMIC RESERVE": "RESERVA ECONÓMICA",
  "fixed blocks": "bloques fijos",
  "Expected extra": "extra esperado",
  "Energy below 3 hours": "Energía por debajo de 3 horas",
  "Confirm your identity": "Confirma tu identidad",
  "Decrease allocation for": "Disminuir la asignación para",
  "DEPOSIT METHODS": "MÉTODOS DE DEPÓSITO",
  "Confirm your email before signing in. You can resend the confirmation from the sign-up screen.": "Confirme su correo electrónico antes de iniciar sesión. Puede reenviar la confirmación desde la pantalla de registro.",
  "Enter the six-digit code shown in your authenticator app to continue.": "Ingrese el código de seis dígitos que se muestra en su aplicación de autenticación para continuar.",
  "Code expired. Wait for the next code in your authenticator app.": "El código expiró. Espere el siguiente código en su aplicación de autenticación.",
  "Does Arcadia create a blockchain wallet for each user?": "¿Arcadia crea una billetera blockchain para cada usuario?",
  "Complete the Arcade Tour to earn your first battery.": "Completa el Arcade Tour para ganar tu primera batería.",
  "Enable power, batteries and CMA with a daily cap.": "Habilite energía, baterías y CMA con un límite diario.",
  "Create your operator and start with your first rack.": "Crea tu operador y comienza con tu primer rack.",
  "Energy active": "Energía activa",
  "CONTINUE SETUP": "CONTINUAR CONFIGURACIÓN",
  "ENABLE PROTECTION": "HABILITAR PROTECCIÓN",
  "FRAUD ALERT": "ALERTA DE FRAUDE",
  "Free + Premium": "Gratis + Premium",
  "I need help": "necesito ayuda",
  "MINER": "MINERO",
  "INTERNAL BALANCE": "SALDO INTERNO",
  "large": "grande",
  "OPEN": "ABIERTO",
  "Incorrect email or password.": "Correo electrónico o contraseña incorrectos.",
  "of cycle": "de ciclo",
  "Internal ID": "Identificación interna",
  "New password": "Nueva contraseña",
  "IN REVIEW": "EN REVISIÓN",
  "MINIMUM": "MÍNIMO",
  "no accumulated balance": "sin saldo acumulado",
  "installed": "instalado",
  "INSTALL": "INSTALAR",
  "GUIDE & ALERTS": "GUÍA Y ALERTAS",
  "miners": "mineros",
  "left": "izquierda",
  "LEVEL": "NIVEL",
  "GLOBAL SERVER NETWORK": "RED GLOBAL DE SERVIDORES",
  "LARGE": "GRANDE",
  "IN PROGRESS": "EN CURSO",
  "LAST QUOTE": "ÚLTIMA COTIZACIÓN",
  "IDENTITY": "IDENTIDAD",
  "NO CAP": "SIN TAPA",
  "How are deposits and withdrawals processed?": "¿Cómo se procesan los depósitos y retiros?",
  "NOW": "AHORA",
  "LINKED SIGNUPS": "INSCRIPCIONES VINCULADAS",
  "NO POWER": "SIN ENERGÍA",
  "Next steps": "Próximos pasos",
  "MY TICKETS": "MIS ENTRADAS",
  "LOADING...": "CARGANDO...",
  "low battery chance": "probabilidad de batería baja",
  "JOIN DISCORD": "ÚNETE A LA DISCORDANCIA",
  "Link copied.": "Enlace copiado.",
  "INTERNAL CONVERSION": "CONVERSIÓN INTERNA",
  "LOADING…": "CARGANDO…",
  "Inventory": "Inventario",
  "How a confirmation appears in your account": "Cómo aparece una confirmación en tu cuenta",
  "Mining arcade": "Galería minera",
  "Minimum R$ 20": "Mínimo R$ 20",
  "OPEN ARCADE": "ARCADE ABIERTA",
  "OPEN INVOICE": "FACTURA ABIERTA",
  "LEVEL PROGRESS": "PROGRESO DE NIVEL",
  "Open rack shop": "tienda de estantes abiertos",
  "Keep the room powered": "Mantenga la habitación encendida",
  "Open rack at position": "Abra la rejilla en la posición",
  "One focused objective": "Un objetivo enfocado",
  "limited CMA fragments": "fragmentos limitados de CMA",
  "Mining paused": "Minería en pausa",
  "New signal soon": "Nueva señal pronto",
  "OF YOUR POWER": "DE TU PODER",
  "MAX · FULL TRACK": "MÁXIMO · PISTA COMPLETA",
  "occupied slots": "espacios ocupados",
  "My profile": "mi perfil",
  "Miners": "mineros",
  "Good practices": "Buenas practicas",
  "No active authenticator was found for this account. Return to your profile and set up protection again.": "No se encontró ningún autenticador activo para esta cuenta. Regrese a su perfil y configure la protección nuevamente.",
  "Next in ${formatEnergy(Math.ceil(cycleRemaining / 1000))}": "Siguiente en ${formatEnergy(Math.ceil(cycleRemaining / 1000))}",
  "If the account exists, a new recovery link was sent.": "Si la cuenta existe, se envió un nuevo enlace de recuperación.",
  "If the account exists, you will receive an email with the next step.": "Si la cuenta existe, recibirá un correo electrónico con el siguiente paso.",
  "Open Inventory and choose equipment for the rack.": "Abra el Inventario y elija el equipo para el bastidor.",
  "of 8 occupied slots": "de 8 plazas ocupadas",
  "Miners and racks": "Mineros y bastidores",
  "Minigames · temporary": "Minijuegos · temporales",
  "IN DESIGN": "EN DISEÑO",
  "No miner installed": "No hay minero instalado",
  "OFFICIAL HELP": "AYUDA OFICIAL",
  "NEXT ACTION": "PRÓXIMA ACCIÓN",
  "Mining status": "Estado minero",
  "MINER ENERGY": "ENERGÍA MINERA",
  "Increase allocation for": "Aumentar la asignación para",
  "NEXT BLOCK": "SIGUIENTE BLOQUE",
  "MANAGE POOLS": "GESTIONAR PISCINAS",
  "Invalid or expired code.": "Código no válido o caducado.",
  "Loading season...": "Temporada de carga...",
  "Install rack at position ${firstEmptyRackPosition + 1}": "Instale el bastidor en la posición ${firstEmptyRackPosition + 1}",
  "Manage your identity, security, and preferences in one place.": "Administre su identidad, seguridad y preferencias en un solo lugar.",
  "Loading your link…": "Cargando tu enlace…",
  "Invite new operators": "Invitar a nuevos operadores",
  "No seed phrase, private key, or wallet password required": "No se requiere frase inicial, clave privada ni contraseña de billetera",
  "No. CMA is an internal game credit and cannot be withdrawn.": "No. CMA es un crédito interno del juego y no se puede retirar.",
  "NEW ARCADIA REPLY": "NUEVA RESPUESTA DE ARCADIA",
  "Install your first rack": "Instale su primer bastidor",
  "New operators start with one rack and one starter miner": "Los nuevos operadores comienzan con un rack y un minero inicial.",
  "If sign-up is still pending, a new confirmation was sent.": "Si el registro aún está pendiente, se envió una nueva confirmación.",
  "of each CMA block": "de cada bloque CMA",
  "INSTALL · ${rackInventoryCount} AVAILABLE": "INSTALAR · ${rackInventoryCount} DISPONIBLE",
  "Invalid or expired code. Check your authenticator app and try again.": "Código no válido o caducado. Verifique su aplicación de autenticación e inténtelo nuevamente.",
  "No balance changes before you confirm.": "No hay cambios de saldo antes de confirmar.",
  "Keep the operation identifier.": "Conserve el identificador de la operación.",
  "of each BTC, DOGE or LTC block": "de cada bloque BTC, DOGE o LTC",
  "Less than one minute until the next settlement.": "Menos de un minuto hasta el próximo acuerdo.",
  "How is the reward calculated?": "¿Cómo se calcula la recompensa?",
  "Manage your coins and buy CMA in one place.": "Administre sus monedas y compre CMA en un solo lugar.",
  "Open rack at position ${positionIndex + 1}": "Abrir rack en la posición ${positionIndex + 1}",
  "Only the rack and Byte Spark are registered": "Sólo se registran el rack y Byte Spark",
  "MULTI-MINING · 10-MINUTE BLOCKS": "MULTIMINERÍA · BLOQUES DE 10 MINUTOS",
  "Install rack at position ${positionIndex + 1}": "Instale el bastidor en la posición ${positionIndex + 1}",
  "Keep energy and power active": "Mantén la energía y el poder activos.",
  "Invalid code. Check your authenticator app and try again.": "Código no válido. Verifique su aplicación de autenticación e inténtelo nuevamente.",
  "PAUSED": "PAUSADO",
  "Open support": "Soporte abierto",
  "Security": "Seguridad",
  "or use your email": "o usa tu correo electrónico",
  "SECURITY": "SEGURIDAD",
  "OPEN SHOP": "TIENDA ABIERTA",
  "PROCESSING...": "TRATAMIENTO...",
  "RESOLVED": "RESUELTO",
  "Privacy": "Privacidad",
  "ORGANIZE": "ORGANIZAR",
  "ROOM": "HABITACIÓN",
  "SENDING…": "ENVÍO…",
  "Password": "Contraseña",
  "Protocol": "Protocolo",
  "READING": "LECTURA",
  "Recover password": "recuperar contraseña",
  "POWER": "FUERZA",
  "Replies are tracked in your account": "Las respuestas se rastrean en su cuenta",
  "RESEND IN ${resendSeconds}s": "REENVÍO EN ${resendSeconds}s",
  "POSITION": "POSICIÓN",
  "RECEIVE IN CRYPTO": "RECIBIR EN CRIPTO",
  "Receive your starter kit": "Recibe tu kit de inicio",
  "Server and anti-fraud": "Servidor y antifraude",
  "Other topic": "Otro tema",
  "safe prototype": "prototipo seguro",
  "Operator name": "Nombre del operador",
  "Operation summary": "Resumen de operación",
  "RECOVER SETUP": "RECUPERAR CONFIGURACIÓN",
  "Operation details": "Detalles de la operación",
  "OPERATOR CENTER": "CENTRO DEL OPERADOR",
  "RESERVING…": "RESERVANDO…",
  "RESEND CODE": "REENVIAR CÓDIGO",
  "Scan with Google Authenticator, Authy, or another compatible app.": "Escanee con Google Authenticator, Authy u otra aplicación compatible.",
  "Progress stays protected and synced across devices": "El progreso permanece protegido y sincronizado en todos los dispositivos",
  "Receive a bonus on every validated block mined by operators who join through your link.": "Reciba una bonificación por cada bloque validado extraído por los operadores que se unan a través de su enlace.",
  "Resets every day": "Se reinicia todos los días",
  "REFRESH STATUS": "ACTUALIZAR ESTADO",
  "RESENDING...": "REENVÍO...",
  "SEASON MISSIONS": "MISIONES DE TEMPORADA",
  "Power the room": "Enciende la habitación",
  "REQUEST WITHDRAWAL": "SOLICITAR RETIRO",
  "SAVE NEW PASSWORD": "GUARDAR NUEVA CONTRASEÑA",
  "OPERATIONAL MARGIN": "MARGEN OPERATIVO",
  "QUICK ALLOCATIONS": "ASIGNACIONES RÁPIDAS",
  "PREMIUM UNLOCKED": "PREMIUM DESBLOQUEADO",
  "REWARDS ISSUED": "RECOMPENSAS EMITIDAS",
  "Operator center sections": "Secciones del centro del operador",
  "PROTOTYPE LOCKED": "PROTOTIPO BLOQUEADO",
  "RESEND IN ${seconds}s": "REENVÍO EN ${segundos}s",
  "Play Packet Catch, Hash Match and Circuit Rush": "Juega Packet Catch, Hash Match y Circuit Rush",
  "PROTECTED ACCOUNT": "CUENTA PROTEGIDA",
  "Play, progress and claim XP": "Juega, progresa y reclama XP",
  "Quick access to this room's racks": "Acceso rápido a los racks de esta sala.",
  "Recover access securely through your email.": "Recupera el acceso de forma segura a través de tu correo electrónico.",
  "RESERVED IN ${brlQuote.asset}": "RESERVADO EN ${brlQuote.asset}",
  "Rare miners and more temporary power": "Mineros raros y más poder temporal",
  "paid as blocks are validated": "pagado a medida que se validan los bloques",
  "Open this only when you need a quick answer.": "Ábrelo sólo cuando necesites una respuesta rápida.",
  "OPERATOR CENTER · PERSONAL PROGRESS": "CENTRO DEL OPERADOR · PROGRESO PERSONAL",
  "Preparing verification...": "Preparando verificación...",
  "Open the full wallet and convert to CMA": "Abra la billetera completa y conviértala a CMA",
  "ORGANIZED AREAS": "ÁREAS ORGANIZADAS",
  "Return to the mining room": "Regreso a la sala de minería.",
  "Resets every week": "Se reinicia cada semana",
  "QR code to configure the authenticator": "Código QR para configurar el autenticador",
  "Reward and ledger synced by the server.": "Recompensa y libro mayor sincronizados por el servidor.",
  "SEASON ENDED": "TEMPORADA FINALIZADA",
  "ROOM RACKS": "ESTANTES DE HABITACIÓN",
  "Problem title": "Título del problema",
  "Protection active": "Protección activa",
  "ORBIT PASS MAX ACTIVE": "ORBIT PASA MAX ACTIVO",
  "SERVER ONLINE": "SERVIDOR EN LÍNEA",
  "Receive your first block": "Recibe tu primer bloque",
  "READY TO APPLY": "LISTO PARA APLICAR",
  "SECURE SUPPORT": "SOPORTE SEGURO",
  "Season unavailable.": "Temporada no disponible.",
  "Select BTC, DOGE, or LTC in your wallet and check the amount before paying.": "Seleccione BTC, DOGE o LTC en su billetera y verifique el monto antes de pagar.",
  "Payment in Brazilian reais": "Pago en reales brasileños",
  "POWER DISTRIBUTION · POOLS": "DISTRIBUCIÓN DE ENERGÍA · PISCINAS",
  "RESEND EMAIL": "REENVIAR CORREO ELECTRÓNICO",
  "Repeat the password with at least 10 characters.": "Repita la contraseña con al menos 10 caracteres.",
  "SEASON 01 · SPACE RACE": "TEMPORADA 01 · CARRERA ESPACIAL",
  "Reward recorded in your history": "Recompensa registrada en tu historial",
  "Progress by completing server-validated rounds.": "Progresa completando rondas validadas por el servidor.",
  "RECENT INVOICES · LAST 30 DAYS": "FACTURAS RECIENTES · ÚLTIMOS 30 DÍAS",
  "REFERRAL PROGRAM · SHARED MINING": "PROGRAMA DE REFERENCIA · MINERÍA COMPARTIDA",
  "RECOVER PASSWORD": "RECUPERAR CONTRASEÑA",
  "Referrals unavailable.": "Referencias no disponibles.",
  "Season missions": "Misiones de temporada",
  "Open the room": "abre la habitacion",
  "Quote unavailable": "Cotización no disponible",
  "OPERATIONS": "OPERACIONES",
  "Password updated. Redirecting to your operation...": "Contraseña actualizada. Redirigiendo a su operación...",
  "Open virtual wallet": "Abrir billetera virtual",
  "RECOVERY REQUESTED": "RECUPERACIÓN SOLICITADA",
  "Season updated.": "Temporada actualizada.",
  "PER BLOCK": "POR BLOQUE",
  "REWARD TRACKS": "PISTAS DE RECOMPENSA",
  "Percentage allocated to": "Porcentaje asignado a",
  "SEND RECOVERY LINK": "ENVIAR ENLACE DE RECUPERACIÓN",
  "Wallet": "Billetera",
  "SHOP": "COMERCIO",
  "SIGN IN": "INICIAR SESIÓN",
  "VERIFYING…": "VERIFICANDO…",
  "START YOUR OPERATION": "COMIENCE SU OPERACIÓN",
  "WAIT": "ESPERAR",
  "Text size": "Tamaño del texto",
  "Waiting for quote": "Esperando cotización",
  "Swipe and tap to manage": "Desliza y toca para administrar",
  "VERIFIED ACCOUNT": "CUENTA VERIFICADA",
  "Ticket created.": "Boleto creado.",
  "TEMPORARY POWER": "PODER TEMPORAL",
  "Sign in": "Iniciar sesión",
  "Skip tour": "Saltar recorrido",
  "VALIDATING ON SERVER…": "VALIDANDO EN EL SERVIDOR…",
  "steps": "pasos",
  "UPDATING...": "ACTUALIZANDO...",
  "System status": "Estado del sistema",
  "SUPPORT CENTER": "CENTRO DE SOPORTE",
  "SIGN UP": "INSCRIBIRSE",
  "to the next level": "al siguiente nivel",
  "Two-step authentication": "Autenticación en dos pasos",
  "STEP": "PASO",
  "Temporary minigame power": "Poder temporal de minijuego",
  "Use or claim a battery": "Usar o reclamar una batería",
  "USE BATTERY": "USAR BATERÍA",
  "useful alert(s)": "alerta(s) útiles",
  "Support": "Apoyo",
  "Visit the Arcade": "Visita la sala de juegos",
  "UPDATING…": "ACTUALIZANDO…",
  "Ticket was not sent.": "El billete no fue enviado.",
  "SWITCH ROOM": "CAMBIAR DE HABITACIÓN",
  "UPGRADE MAX": "ACTUALIZAR MÁXIMO",
  "valid until": "válido hasta",
  "Wallet balances": "Saldos de billetera",
  "SYSTEM ONLINE": "SISTEMA EN LÍNEA",
  "We are here to help.": "Estamos aquí para ayudar.",
  "Topic": "Tema",
  "USEFUL INFORMATION": "INFORMACIÓN ÚTIL",
  "SIGN IN TO ARCADIA": "INICIAR SESIÓN EN ARCADIA",
  "SIGN IN TO YOUR ACCOUNT": "INICIA SESIÓN EN TU CUENTA",
  "SUPPORT ACTIVE": "SOPORTE ACTIVO",
  "SIGN OUT": "DESCONECTAR",
  "The response confirms you are human and is not stored.": "La respuesta confirma que eres humano y no se almacena.",
  "The amount, network and minimum are shown before confirmation.": "El importe, la red y el mínimo se muestran antes de la confirmación.",
  "Two-step authentication is active on this account.": "La autenticación de dos pasos está activa en esta cuenta.",
  "Use the six-digit code shown in your authenticator app to complete setup.": "Utilice el código de seis dígitos que se muestra en su aplicación de autenticación para completar la configuración.",
  "The code expires in 10 minutes. MFA remains the strongest protection when enabled.": "El código caduca en 10 minutos. MFA sigue siendo la protección más sólida cuando está habilitada.",
  "We could not update the password. Request a new link.": "No pudimos actualizar la contraseña. Solicite un nuevo enlace.",
  "Variable minimum ≈ R$ 50": "Mínimo variable ≈ R$ 50",
  "Unable to load the season.": "No se puede cargar la temporada.",
  "We could not prepare verification.": "No pudimos preparar la verificación.",
  "Use the battery you earned": "Usa la batería que ganaste",
  "Server-controlled rewards": "Recompensas controladas por el servidor",
  "The pending setup could not be removed. Sign out, sign in again, and try enabling the authenticator.": "No se pudo eliminar la configuración pendiente. Cierre sesión, inicie sesión nuevamente e intente habilitar el autenticador.",
  "The human verification expired. Confirm it again and submit once more.": "La verificación humana expiró. Confírmelo nuevamente y envíelo una vez más.",
  "Use a password with at least 10 characters.": "Utilice una contraseña con al menos 10 caracteres.",
  "Waiting for the next season.": "Esperando la próxima temporada.",
  "The two passwords must match.": "Las dos contraseñas deben coincidir.",
  "VERIFYING...": "VERIFICANDO...",
  "TIMING AND PROOF": "TIEMPO Y PRUEBA",
  "Wallet actions": "Acciones de billetera",
  "Wallet and conversions": "Monedero y conversiones",
  "Status unavailable": "Estado no disponible",
  "Verified session": "Sesión verificada",
  "Track complete": "Pista completa",
  "Track progress and replies on this page.": "Realice un seguimiento del progreso y las respuestas en esta página.",
  "We could not send the code right now.": "No pudimos enviar el código en este momento.",
  "We could not complete that right now. Review the details and try again.": "No pudimos completar eso ahora. Revise los detalles y vuelva a intentarlo.",
  "We could not start verification. Try signing in again.": "No pudimos iniciar la verificación. Intente iniciar sesión nuevamente.",
  "This account already exists. Try signing in or recovering your password.": "Esta cuenta ya existe. Intente iniciar sesión o recuperar su contraseña.",
  "We could not complete setup right now. Try again.": "No pudimos completar la configuración en este momento. Intentar otra vez.",
  "Too many emails were requested. Please wait a few minutes.": "Se solicitaron demasiados correos electrónicos. Espere unos minutos.",
  "Stay ahead of special events": "Manténgase a la vanguardia de eventos especiales",
  "Unable to complete the action.": "No se puede completar la acción.",
  "validated temporary power": "poder temporal validado",
  "Signed sessions, limits and validated scores.": "Sesiones firmadas, límites y puntuaciones validadas.",
  "VIEW PIX WITHDRAWAL QUOTE": "VER COTIZACIÓN DE RETIRADA DE FOTOS",
  "Waiting for amount and ${asset} quote": "Esperando monto y cotización de ${asset}",
  "Validated rounds, missions and limited CMA spending generate XP.": "Las rondas validadas, las misiones y el gasto limitado en CMA generan XP.",
  "Sign-up is temporarily paused while human verification is configured.": "El registro se pausa temporalmente mientras se configura la verificación humana.",
  "This link can be used once. Your new password must have at least 10 characters.": "Este enlace se puede utilizar una vez. Su nueva contraseña debe tener al menos 10 caracteres.",
  "The confirmed balance appears in the same coin ledger, without automatic conversion.": "El saldo confirmado aparece en el mismo libro mayor de monedas, sin conversión automática.",
  "Sign in to return to your room and track your mining.": "Inicia sesión para regresar a tu habitación y realizar un seguimiento de tu minería.",
  "Two-step authentication is still disabled in the Supabase project.": "La autenticación de dos pasos todavía está deshabilitada en el proyecto Supabase.",
  "Verification unavailable.": "Verificación no disponible.",
  "Two-step authentication is disabled.": "La autenticación de dos pasos está deshabilitada.",
  "The current minimum will appear here.": "El mínimo actual aparecerá aquí.",
  "Use an authenticator app to protect access even if your password is discovered.": "Utilice una aplicación de autenticación para proteger el acceso incluso si se descubre su contraseña.",
  "The previous setup is pending with the provider. Use recovery below to clear only the unconfirmed factor and start again.": "La configuración anterior está pendiente con el proveedor. Utilice la recuperación a continuación para borrar solo el factor no confirmado y comenzar de nuevo.",
  "Sign in to create a secure ticket.": "Inicia sesión para crear un ticket seguro.",
  "We could not complete that right now. Try again.": "No pudimos completar eso ahora. Intentar otra vez.",
  "We could not create the ticket.": "No pudimos crear el ticket.",
  "Sign-up received. Confirm your email to unlock the account.": "Registro recibido. Confirma tu correo electrónico para desbloquear la cuenta.",
  "Sign-up is paused because the email service is unavailable. No account was created. Try again later or contact support.": "El registro está en pausa porque el servicio de correo electrónico no está disponible. No se creó ninguna cuenta. Vuelva a intentarlo más tarde o comuníquese con el soporte.",
  "Total network power": "Potencia total de la red",
  "TOTAL ALLOCATED": "TOTAL ASIGNADO",
  "VALIDATING...": "VALIDANDO...",
  "TOTAL EFFECTIVE POWER": "POTENCIA EFECTIVA TOTAL",
  "The passwords do not match. Check both fields.": "Las contraseñas no coinciden. Marque ambos campos.",
  "What happened?": "¿Qué pasó?",
  "WEEKLY": "SEMANALMENTE",
  "Your share per block": "Tu parte por bloque",
  "Your account tickets": "Tus billetes de cuenta",
  "WEEKLY SIGNAL": "SEÑAL SEMANAL",
  "YOU WILL RECEIVE": "RECIBIRÁS",
  "YOU WILL PAY APPROXIMATELY": "PAGARÁS APROXIMADAMENTE",
  "We could not validate the code right now.": "No pudimos validar el código en este momento.",
  "WITHDRAWAL · MANUAL PROCESSING": "RETIRO · TRAMITACIÓN MANUAL",
  "Your mining operation starts here.": "Su operación minera comienza aquí.",
  "YOU RECEIVE": "USTED RECIBE",
  "Your first operation is ready": "Tu primera operación está lista",
  "Your progress is verified": "Tu progreso está verificado",
  "Your session expired. Sign in again to continue.": "Tu sesión expiró. Inicia sesión nuevamente para continuar.",
  "We could not validate two-step protection. Try signing in again.": "No pudimos validar la protección de dos pasos. Intente iniciar sesión nuevamente.",
  "Your Arcadia career": "Tu carrera en Arcadia",
  "Your session expired. Sign in again to configure protection.": "Tu sesión expiró. Inicie sesión nuevamente para configurar la protección.",
  "WHOLE CMA UNITS": "UNIDADES COMPLETAS DE CMA",
  "XP claimed!": "¡XP reclamado!",
  "What is already defined": "lo que ya esta definido",
  "Weekly challenge": "desafío semanal",
  "Your share:": "Tu parte:",
  "Your energy is empty. Use a battery to resume production.": "Tu energía está vacía. Utilice una batería para reanudar la producción.",
  "Your tickets will appear here after your first submission.": "Sus boletos aparecerán aquí después de su primer envío.",
  "XP is shared between the free and premium tracks.": "XP se comparte entre las pistas gratuitas y premium.",
  "Your requests and replies stay together on this page.": "Sus solicitudes y respuestas permanecen juntas en esta página.",
  "Account and access": "Cuenta y acceso",
  "Cookie Policy": "Política de cookies",
  "Game and inventory": "Juego e inventario",
  "Complete the Arcade Tour": "Completa el recorrido arcade",
  "CMA is an internal credit used for in-game purchases and progression. It is not an external cryptocurrency and cannot be withdrawn.": "CMA es un crédito interno que se utiliza para compras y progresión dentro del juego. No es una criptomoneda externa y no se puede retirar.",
  "CMA is an internal credit for purchases and progression and cannot be withdrawn. BTC, DOGE and LTC deposits, when available, depend on the selected network, payment provider, on-chain confirmation, limits and fees. Funds are credited only after a valid confirmation and may be reviewed for security.": "CMA es un crédito interno para compras y progresión y no se puede retirar. Los depósitos de BTC, DOGE y LTC, cuando estén disponibles, dependen de la red seleccionada, el proveedor de pago, la confirmación en cadena, los límites y las tarifas. Los fondos se acreditan únicamente después de una confirmación válida y pueden revisarse por motivos de seguridad.",
  "After a deposit is confirmed, choose the currency, enter a whole CMA amount and review the server quote before confirming the conversion.": "Después de confirmar un depósito, elija la moneda, ingrese un monto total de CMA y revise la cotización del servidor antes de confirmar la conversión.",
  "Arcadia does not activate ads, advertising scripts or advertising cookies at this stage. If measurement or advertising is added later, it will be documented by purpose and consented to where required.": "Arcadia no activa anuncios, scripts publicitarios ni cookies publicitarias en esta etapa. Si se agregan mediciones o publicidad más adelante, se documentará según el propósito y se consentirá cuando sea necesario.",
  "Authenticated Arcade wins, missions and eligible activities grant XP. Progress is linked to your account and cannot be fabricated by the client.": "Las victorias, misiones y actividades elegibles de Arcade autenticadas otorgan XP. El progreso está vinculado a su cuenta y el cliente no puede fabricarlo.",
  "Cloudflare may process traffic, protection and hosting; Supabase may process authentication and database services; email and payment providers process the data required for their flows. We share only what is needed to operate the service, comply with law or protect users.": "Cloudflare puede procesar tráfico, protección y alojamiento; Supabase podrá procesar servicios de autenticación y de bases de datos; Los proveedores de correo electrónico y pagos procesan los datos necesarios para sus flujos. Compartimos solo lo que se necesita para operar el servicio, cumplir con la ley o proteger a los usuarios.",
  "Compromised accounts, fraud attempts, fake sites, or suspicious automated activity.": "Cuentas comprometidas, intentos de fraude, sitios falsos o actividad automatizada sospechosa.",
  "DOCUMENT 01": "DOCUMENTO 01",
  "How do withdrawals work?": "¿Cómo funcionan los retiros?",
  "Abrir pools": "Abrir piscinas",
  "How we use data": "Cómo utilizamos los datos",
  "DOCUMENT 05": "DOCUMENTO 05",
  "1. Nature of the service": "1. Naturaleza del servicio",
  "Document sections": "Secciones del documento",
  "Conquiste energia": "Conquista energia",
  "Confirme sua pool": "Confirma tu piscina",
  "DOCUMENT 03": "DOCUMENTO 03",
  "Conta e acesso": "Contacto y acceso",
  "5. Seasons and rewards": "5. Temporadas y recompensas",
  "Acompanhe seus blocos": "Acompaña tus blocos",
  "DOCUMENT 02": "DOCUMENTO 02",
  "Frequently asked questions, without the noise.": "Preguntas frecuentes, sin ruido.",
  "Are season rewards permanent?": "¿Las recompensas de temporada son permanentes?",
  "Check the invoice ID, network and public transaction hash. If the status does not change within the stated time, open a Support ticket with those details; never send a password or private key.": "Verifique el ID de la factura, la red y el hash de transacciones públicas. Si el estado no cambia dentro del tiempo indicado, abra un ticket de soporte con esos detalles; nunca envíe una contraseña o clave privada.",
  "4. Fair play and security": "4. Juego limpio y seguridad",
  "6. Availability and support": "6. Disponibilidad y soporte",
  "In Pools, distribute power across CMA, Bitcoin, Dogecoin, and Litecoin. Each block has a fixed reward.": "En Pools, distribuya energía entre CMA, Bitcoin, Dogecoin y Litecoin. Cada bloque tiene una recompensa fija.",
  "2. Account and eligibility": "2. Cuenta y elegibilidad",
  "Games, energy and batteries": "Juegos, energía y pilas.",
  "How do I convert BTC, DOGE or LTC to CMA?": "¿Cómo convierto BTC, DOGE o LTC a CMA?",
  "Both use the same XP level. Premium unlocks the paid track and also unlocks free rewards already reached at that level.": "Ambos usan el mismo nivel de XP. Premium desbloquea la pista paga y también desbloquea recompensas gratuitas ya alcanzadas en ese nivel.",
  "Clear documents for safer play.": "Documentos claros para un juego más seguro.",
  "BTC, DOGE and LTC requests enter a review queue. The status, currency and payment reference remain visible in your account statement.": "Las solicitudes de BTC, DOGE y LTC ingresan a una cola de revisión. El estado, la moneda y la referencia de pago permanecen visibles en su estado de cuenta.",
  "Escolha onde seu poder trabalha": "Escola onde su poder trabajar",
  "How does the Arcade grant power?": "¿Cómo otorga poder el Arcade?",
  "Does Arcadia store my private key?": "¿Arcadia almacena mi clave privada?",
  "Advertising and measurement": "Publicidad y medición",
  "Deposits, withdrawals and support": "Depósitos, retiros y soporte",
  "Arcadia is a digital entertainment platform. CMA, power, miners, energy and rewards are virtual game elements: they are not an investment, equity interest or promise of returns.": "Arcadia es una plataforma de entretenimiento digital. CMA, potencia, mineros, energía y recompensas son elementos del juego virtual: no son una inversión, participación accionaria ni promesa de rentabilidad.",
  "Batteries extend the miners' energy cycle. The room's free cycle is separate from Arcade XP and follows the current energy rules.": "Las baterías amplían el ciclo energético de los mineros. El ciclo gratuito de la sala es independiente del Arcade XP y sigue las reglas energéticas actuales.",
  "Arcadia provides digital entertainment. It does not promise profit, return, CMA appreciation or recovery of amounts spent on virtual items. Only use funds you can afford to lose.": "Arcadia ofrece entretenimiento digital. No promete ganancias, retornos, apreciación de CMA o recuperación de montos gastados en artículos virtuales. Utilice únicamente fondos que pueda permitirse perder.",
  "Data we use": "Datos que utilizamos",
  "BEFORE YOU OPERATE": "ANTES DE OPERAR",
  "GO TO SUPPORT": "IR A SOPORTE",
  "Go to minigames": "Ir a minijuegos",
  "Arcadia rights": "Derechos de Arcadia",
  "Confirm your pool": "Confirma tu piscina",
  "Carteira e depósitos": "Carteira y depósitos",
  "7. Business information": "7. Información comercial",
  "Essential cookies": "Galletas esenciales",
  "3. Economy and payments": "3. Economía y pagos",
  "Abrir rack": "Abrir estante",
  "How do I earn XP?": "¿Cómo gano XP?",
  "Crypto and conversions": "Cripto y conversiones",
  "How do I make a deposit?": "¿Cómo hago un depósito?",
  "Earn energy": "Gana energía",
  "DOCUMENT 04": "DOCUMENTO 04",
  "Cryptocurrency names, marks and symbols belong to their respective owners and do not imply endorsement. Third-party assets used in the product must be licensed or authorized for the intended use.": "Los nombres, marcas y símbolos de las criptomonedas pertenecen a sus respectivos propietarios y no implican respaldo. Los activos de terceros utilizados en el producto deben tener licencia o autorización para el uso previsto.",
  "Arcade power has a server-defined validity period. Regular play maintains activity; permanent miner power remains while equipment is installed, powered and valid.": "Arcade power tiene un período de validez definido por el servidor. El juego regular mantiene la actividad; La energía minera permanente permanece mientras el equipo está instalado, encendido y válido.",
  "Essential cookies and local storage keep the session, language preference and reading options. They are required for authentication and basic account operation.": "Las cookies esenciales y el almacenamiento local mantienen la sesión, la preferencia de idioma y las opciones de lectura. Son necesarios para la autenticación y la operación básica de la cuenta.",
  "Find the Crypto Miner Arcadia rules for use, privacy, cookies, risk and intellectual property in one place.": "Encuentre las reglas de uso, privacidad, cookies, riesgo y propiedad intelectual de Crypto Miner Arcadia en un solo lugar.",
  "Email confirmation, password recovery, device changes, and account progress linking.": "Confirmación por correo electrónico, recuperación de contraseña, cambios de dispositivo y vinculación del progreso de la cuenta.",
  "Each room has twelve free rack positions. A one-fan miner uses one slot; two-fan models require two contiguous slots in the same rack.": "Cada sala dispone de doce posiciones de rack libres. Un minero de un solo ventilador usa una ranura; Los modelos de dos ventiladores requieren dos ranuras contiguas en el mismo bastidor.",
  "Complete o Tour do Arcade": "Completo o Tour do Arcade",
  "Does more power change the block value?": "¿Más potencia cambia el valor del bloque?",
  "Crypto Miner Arcadia is a virtual mining game. Rooms, racks, miners, energy, power, CMA and season items are part of the digital experience and may follow balancing rules. No game item represents a bank deposit, security or guaranteed return.": "Crypto Miner Arcadia es un juego de minería virtual. Habitaciones, bastidores, mineros, energía, potencia, CMA y elementos de temporada son parte de la experiencia digital y pueden seguir reglas de equilibrio. Ningún artículo del juego representa un depósito bancario, una garantía o una devolución garantizada.",
  "How does the referral link work?": "¿Cómo funciona el enlace de referencia?",
  "How do rooms and racks work?": "¿Cómo funcionan las salas y racks?",
  "Choose where your power works": "Elige dónde funciona tu poder",
  "Bots, scripts, click automation, client tampering, exploiting bugs, coordinated accounts used to bypass limits, fraudulent chargebacks and falsifying a game result are prohibited. The server may limit, review or suspend actions when abuse signals appear, while preserving required records.": "Están prohibidos los bots, scripts, automatización de clics, manipulación de clientes, explotación de errores, cuentas coordinadas utilizadas para eludir límites, devoluciones de cargos fraudulentas y falsificación de resultados de juegos. El servidor podrá limitar, revisar o suspender acciones cuando aparezcan señales de abuso, conservando los registros requeridos.",
  "If a cycle closes without at least one validated win, the PC and its play progress return to level 0. You must play and win again to rebuild the progression.": "Si un ciclo se cierra sin al menos una victoria validada, el PC y su progreso de juego regresan al nivel 0. Debes jugar y ganar nuevamente para reconstruir la progresión.",
  "Intellectual Property": "Propiedad Intelectual",
  "Receive your first block": "Recibe tu primer bloque",
  "Wallet and deposits": "Monedero y depósitos",
  "Terms of Use": "Condiciones de uso",
  "Privacy Policy": "política de privacidad",
  "Starter kit delivered": "Kit de inicio entregado",
  "OPERATOR GUIDE": "GUÍA DEL OPERADOR",
  "RULES AND TRANSPARENCY": "NORMAS Y TRANSPARENCIA",
  "Install Byte Spark": "Instalar Byte Spark",
  "Risk Disclosure": "Divulgación de riesgos",
  "No. Arcadia records balances and events in an account ledger; never request or share a seed phrase, password or remote access.": "No. Arcadia registra saldos y eventos en un libro mayor de cuentas; nunca solicite ni comparta una frase inicial, contraseña o acceso remoto.",
  "Minimums, network fees and quotes are shown per currency and may change. The deposit screen shows the correct network, minimum and invoice validity before you send.": "Los mínimos, tarifas de red y cotizaciones se muestran por moneda y pueden cambiar. La pantalla de depósito muestra la red correcta, el mínimo y la validez de la factura antes de enviar.",
  "Include your account, invoice or game ID and what happened. Never send a password, authentication code or private key.": "Incluye tu cuenta, factura o ID del juego y lo que pasó. Nunca envíe una contraseña, código de autenticación o clave privada.",
  "Short answers about operations, the Arcade, energy, the economy, wallets and seasons. Your account state and the server rules always take priority.": "Respuestas breves sobre operaciones, Arcade, energía, economía, billeteras y temporadas. El estado de tu cuenta y las reglas del servidor siempre tienen prioridad.",
  "The server syncs your operation and shows each processed block in the corner of the screen. Your balance is recorded in the wallet ledger.": "El servidor sincroniza su operación y muestra cada bloque procesado en la esquina de la pantalla. Su saldo se registra en el libro mayor de la billetera.",
  "Retention and your rights": "Retención y tus derechos",
  "Your starter kit is in the room": "Tu kit de inicio está en la habitación.",
  "What happens if I go one cycle without a win?": "¿Qué pasa si paso un ciclo sin ganar?",
  "My deposit did not appear. What should I do?": "Mi depósito no apareció. ¿Qué tengo que hacer?",
  "Why can the minimum change?": "¿Por qué puede cambiar el mínimo?",
  "Why does my temporary power decrease?": "¿Por qué disminuye mi poder temporal?",
  "Jogue para ativar energia": "Juego para activar energia",
  "You received a rack and a starter miner. Open the rack to install Byte Spark and begin your operation.": "Recibiste un bastidor y un minero inicial. Abra el rack para instalar Byte Spark y comience su operación.",
  "Send only the asset and network shown on the invoice or withdrawal screen. A wrong network, address or missing memo can cause permanent loss and may not be recoverable by Arcadia or the provider.": "Envíe solo el activo y la red que se muestran en la pantalla de factura o retiro. Una red, una dirección incorrecta o una nota faltante pueden causar una pérdida permanente y es posible que Arcadia o el proveedor no puedan recuperarlos.",
  "It is the capacity used to compete for a share of each block. Miners and racks provide permanent power; authenticated Arcade games may provide temporary power.": "Es la capacidad utilizada para competir por una participación de cada bloque. Los mineros y los bastidores proporcionan energía permanente; Los juegos Arcade autenticados pueden proporcionar energía temporal.",
  "The game must finish within its limits, without automated behavior, and pass server validation. Reloading the page does not replace an authoritative confirmation.": "El juego debe finalizar dentro de sus límites, sin comportamiento automatizado y pasar la validación del servidor. Recargar la página no reemplaza una confirmación autorizada.",
  "Racks, miners, energy, rooms, minigames, rewards, and history discrepancies.": "Bastidores, mineros, energía, salas, minijuegos, recompensas y discrepancias históricas.",
  "The official support channel is support@cryptominerarcadia.com. Corporate name, address and applicable forum will be published or updated before commercial operation in each jurisdiction. Mandatory rules in the user’s location still apply.": "El canal de soporte oficial es support@cryptominerarcadia.com. La razón social, la dirección y el foro aplicable se publicarán o actualizarán antes de la operación comercial en cada jurisdicción. Se siguen aplicando reglas obligatorias en la ubicación del usuario.",
  "What is the difference between the free and premium pass?": "¿Cuál es la diferencia entre el pase gratuito y premium?",
  "Payment providers and networks may delay, reject or review a transaction. Limits, identity checks, regional restrictions, taxes and reporting duties may apply to the user.": "Los proveedores y redes de pago pueden retrasar, rechazar o revisar una transacción. Es posible que se apliquen al usuario límites, controles de identidad, restricciones regionales, impuestos y obligaciones de presentación de informes.",
  "When an account joins through your link and passes the security checks, you receive a bonus for every block it validates: 8% in CMA and 5% in BTC, DOGE and LTC. The invited operator keeps the full reward for their own block; the bonus is not accumulated and does not change the fixed block value.": "Cuando una cuenta se une a través de tu enlace y pasa los controles de seguridad, recibes una bonificación por cada bloque que valida: 8% en CMA y 5% en BTC, DOGE y LTC. El operador invitado se queda con la recompensa completa de su propio bloque; el bono no se acumula y no cambia el valor del bloque fijo.",
  "You must provide a valid email, protect your credentials and use one personal account. Access involving financial features is intended for users aged 18 or the higher legal age that applies where they live. Never share your password, authentication code or account access.": "Debe proporcionar un correo electrónico válido, proteger sus credenciales y utilizar una cuenta personal. El acceso a funciones financieras está destinado a usuarios mayores de 18 años o la edad legal superior que corresponda en su lugar de residencia. Nunca comparta su contraseña, código de autenticación o acceso a la cuenta.",
  "Invoice status, BTC/DOGE/LTC confirmations, CMA conversion, and credit disputes.": "Estado de la factura, confirmaciones de BTC/DOGE/LTC, conversión de CMA y disputas de crédito.",
  "No. Each pool uses a fixed emission per ten-minute block. More power only changes the relative share between operators.": "No. Cada grupo utiliza una emisión fija por bloque de diez minutos. Más potencia sólo cambia la proporción relativa entre operadores.",
  "Open Wallet, choose a currency and create an invoice. Send only the currency and network displayed on the invoice; the credit appears after the provider confirms it.": "Abra Wallet, elija una moneda y cree una factura. Enviar únicamente la moneda y la red que se muestran en la factura; el crédito aparece después de que el proveedor lo confirma.",
  "Open pools": "piscinas abiertas",
  "Ir para minigames": "Ir a minijuegos",
  "Kit entregue": "kit entregue",
  "What is CMA?": "¿Qué es la CMA?",
  "It depends on the item. Miners and inventory items remain on the account; temporary power and energy expire according to the validity shown when claimed.": "Depende del artículo. Los mineros y los artículos del inventario permanecen en la cuenta; La potencia y la energía temporales caducan de acuerdo con la validez que se muestra cuando se reclama.",
  "Instale o Byte Spark": "Instalar Byte Spark",
  "Reviews and restrictions": "Revisiones y restricciones",
  "What are batteries for?": "¿Para qué sirven las baterías?",
  "PUBLIC DOCUMENTATION": "DOCUMENTACIÓN PÚBLICA",
  "Play to activate energy": "Juega para activar la energía.",
  "What is mining power?": "¿Qué es el poder minero?",
  "Open rack": "estante abierto",
  "XP, missions, passes, energy and temporary power follow the rules shown in the game and server validation. Permanent items remain in inventory; temporary rewards expire according to the validity shown at claim. Rules and values may change for future events and blocks with appropriate notice.": "XP, misiones, pases, energía y poder temporal siguen las reglas que se muestran en el juego y la validación del servidor. Los artículos permanentes permanecen en el inventario; Las recompensas temporales caducan según la validez que se muestra en el reclamo. Las reglas y valores pueden cambiar para eventos y bloques futuros con el aviso correspondiente.",
  "Power can be distributed between CMA, Bitcoin, Dogecoin and Litecoin. Distribution is set on the Pools page and applies to valid account power.": "La energía se puede distribuir entre CMA, Bitcoin, Dogecoin y Litecoin. La distribución se establece en la página Grupos y se aplica al poder válido de la cuenta.",
  "We use data to create and protect accounts, operate the game, validate games, calculate rewards, process payments, prevent abuse, answer support requests, fix errors and meet legal obligations. We do not sell personal data as a marketing list.": "Usamos datos para crear y proteger cuentas, operar el juego, validar juegos, calcular recompensas, procesar pagos, prevenir abusos, responder solicitudes de soporte, corregir errores y cumplir obligaciones legales. No vendemos datos personales como una lista de marketing.",
  "We use HTTPS, verified sessions, server authorization, abuse protection, rate limits, idempotent operations, audit trails and recovery copies. No internet-connected system is infallible; incidents are handled and communicated under applicable rules.": "Usamos HTTPS, sesiones verificadas, autorización del servidor, protección contra abusos, límites de velocidad, operaciones idempotentes, pistas de auditoría y copias de recuperación. Ningún sistema conectado a Internet es infalible; Los incidentes son tratados y comunicados bajo las normas aplicables.",
  "Visible operational history may be limited to 30 days. Financial, security, support and audit records may be kept longer when needed for fraud prevention, reconciliation or legal obligations. You may request access, correction or deletion through Support, subject to required retention.": "El historial operativo visible puede limitarse a 30 días. Los registros financieros, de seguridad, de soporte y de auditoría se pueden conservar por más tiempo cuando sea necesario para la prevención del fraude, la conciliación o las obligaciones legales. Puede solicitar acceso, corrección o eliminación a través de Soporte, sujeto a la retención requerida.",
  "Minigames validate your activity and release energy to keep your miners running.": "Los minijuegos validan tu actividad y liberan energía para mantener a tus mineros en funcionamiento.",
  "Not an investment": "No es una inversión",
  "XP and Orbit Pass": "XP y pase de órbita",
  "STILL NEED HELP?": "¿AÚN NECESITAS AYUDA?",
  "Track your blocks": "Sigue tus bloques",
  "View operation": "Ver operación",
  "Ver operação": "Ver operación",
  "Networks and addresses": "Redes y direcciones",
  "Jogo e inventário": "Juego e inventario",
  "Receba o primeiro bloco": "Receba o primeiro bloco",
  "Rooms, racks and power": "Habitaciones, racks y potencia.",
  "Providers and sharing": "Proveedores y compartir",
  "Prices, fees, liquidity, confirmation times and availability for BTC, DOGE and LTC vary. A confirmed conversion may be irreversible. The displayed value is an operational quote at that time, not a promise of a future price.": "Los precios, tarifas, liquidez, tiempos de confirmación y disponibilidad de BTC, DOGE y LTC varían. Una conversión confirmada puede ser irreversible. El valor mostrado es una cotización operativa en ese momento, no una promesa de un precio futuro.",
  "Which pools are available?": "¿Qué piscinas están disponibles?",
  "UPDATED · AUGUST 15, 2026": "ACTUALIZADO · 15 DE AGOSTO DE 2026",
  "Third-party marks and assets": "Marcas y activos de terceros",
  "Open a ticket with the right context.": "Abra un ticket con el contexto adecuado.",
  "Maintenance, provider delays and network outages can occur. Arcadia does not guarantee uninterrupted operation. To dispute a charge or request help, use Support and include the protocol ID; never send a private key or seed phrase.": "Pueden producirse mantenimientos, retrasos en los proveedores y cortes de red. Arcadia no garantiza el funcionamiento ininterrumpido. Para disputar un cargo o solicitar ayuda, utilice Soporte e incluya el ID del protocolo; nunca envíe una clave privada o una frase inicial.",
  "Pools, blocks and conversion": "Piscinas, bloques y conversión.",
  "Seu kit já está na sala": "Tu kit ya está en la sala",
  "Why might a game not grant a reward?": "¿Por qué un juego podría no otorgar una recompensa?",
  "Results are validated by the server. The active PC level sets each temporary reward's lifetime: level 1 lasts 1 day, level 2 lasts 2, level 3 lasts 3, level 4 lasts 4 and level 5 lasts 5 days. Each grant has its own expiry and does not change miner batteries.": "Los resultados son validados por el servidor. El nivel de PC activo establece la duración de cada recompensa temporal: el nivel 1 dura 1 día, el nivel 2 dura 2, el nivel 3 dura 3, el nivel 4 dura 4 y el nivel 5 dura 5 días. Cada subvención tiene su propio vencimiento y no cambia las baterías de los mineros.",
  "We may process email, operator name, session, technical identifiers, language, progress, inventory, games, balances, ledger records, invoice IDs, support protocols and security signals. Arcadia never asks for a password, seed phrase or private key.": "Podemos procesar correo electrónico, nombre del operador, sesión, identificadores técnicos, idioma, progreso, inventario, juegos, saldos, registros del libro mayor, ID de facturas, protocolos de soporte y señales de seguridad. Arcadia nunca solicita una contraseña, frase inicial o clave privada.",
};
